// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller, createStreamingCaller } from 'zitejs/caller';

import type { default as _AiAssistantEp } from '../src/api/aiAssistant';
import type { default as _AnalyzeDocumentEp } from '../src/api/analyzeDocument';
import type { default as _ApproveFinancingRequestEp } from '../src/api/approveFinancingRequest';
import type { default as _ApproveLimitProposalEp } from '../src/api/approveLimitProposal';
import type { default as _AssessFinancingRequestEp } from '../src/api/assessFinancingRequest';
import type { default as _AssessLimitProposalEp } from '../src/api/assessLimitProposal';
import type { default as _CalculatePenaltiesEp } from '../src/api/calculatePenalties';
import type { default as _ComputeCreditScoresEp } from '../src/api/computeCreditScores';
import type { default as _CreateInvitationEp } from '../src/api/createInvitation';
import type { default as _CreatePartnerEp } from '../src/api/createPartner';
import type { default as _CreateProgramEp } from '../src/api/createProgram';
import type { default as _DisburseFinancingRequestEp } from '../src/api/disburseFinancingRequest';
import type { default as _ExportTableCsvEp } from '../src/api/exportTableCsv';
import type { default as _GenerateApiKeyEp } from '../src/api/generateApiKey';
import type { default as _GenerateBrochurePdfEp } from '../src/api/generateBrochurePdf';
import type { default as _GenerateOfferLetterPdfEp } from '../src/api/generateOfferLetterPdf';
import type { default as _GeneratePitchDeckPdfEp } from '../src/api/generatePitchDeckPdf';
import type { default as _GenerateRemindersEp } from '../src/api/generateReminders';
import type { default as _GetAssetSchedulesEp } from '../src/api/getAssetSchedules';
import type { default as _GetBackofficeNotificationsEp } from '../src/api/getBackofficeNotifications';
import type { default as _GetBackofficeUsersEp } from '../src/api/getBackofficeUsers';
import type { default as _GetComplianceAlertsEp } from '../src/api/getComplianceAlerts';
import type { default as _GetCreditScoresEp } from '../src/api/getCreditScores';
import type { default as _GetCurrentUserRoleEp } from '../src/api/getCurrentUserRole';
import type { default as _GetEntitiesForReviewEp } from '../src/api/getEntitiesForReview';
import type { default as _GetEntityBankAccountsEp } from '../src/api/getEntityBankAccounts';
import type { default as _GetEntityDetailEp } from '../src/api/getEntityDetail';
import type { default as _GetFiLedgerEp } from '../src/api/getFiLedger';
import type { default as _GetFiLoansEp } from '../src/api/getFiLoans';
import type { default as _GetFiScreeningQueueEp } from '../src/api/getFiScreeningQueue';
import type { default as _GetFinancialInstitutionsEp } from '../src/api/getFinancialInstitutions';
import type { default as _GetFinancingRequestDetailEp } from '../src/api/getFinancingRequestDetail';
import type { default as _GetFinancingRequestsListEp } from '../src/api/getFinancingRequestsList';
import type { default as _GetInvitationsEp } from '../src/api/getInvitations';
import type { default as _GetInvoiceDetailEp } from '../src/api/getInvoiceDetail';
import type { default as _GetInvoicesListEp } from '../src/api/getInvoicesList';
import type { default as _GetLimitProposalsListEp } from '../src/api/getLimitProposalsList';
import type { default as _GetLoanDetailEp } from '../src/api/getLoanDetail';
import type { default as _GetOfferLettersListEp } from '../src/api/getOfferLettersList';
import type { default as _GetOnboardingDetailEp } from '../src/api/getOnboardingDetail';
import type { default as _GetOnboardingsListEp } from '../src/api/getOnboardingsList';
import type { default as _GetOverdueLoansEp } from '../src/api/getOverdueLoans';
import type { default as _GetOverviewEp } from '../src/api/getOverview';
import type { default as _GetPartnerDetailEp } from '../src/api/getPartnerDetail';
import type { default as _GetPartnerEntitiesEp } from '../src/api/getPartnerEntities';
import type { default as _GetPartnerFinancingEp } from '../src/api/getPartnerFinancing';
import type { default as _GetPartnerInvoicesEp } from '../src/api/getPartnerInvoices';
import type { default as _GetPartnerLoansEp } from '../src/api/getPartnerLoans';
import type { default as _GetPartnerOverviewEp } from '../src/api/getPartnerOverview';
import type { default as _GetPartnerProgramsEp } from '../src/api/getPartnerPrograms';
import type { default as _GetPartnerTransactionsEp } from '../src/api/getPartnerTransactions';
import type { default as _GetPartnersListEp } from '../src/api/getPartnersList';
import type { default as _GetProgramDetailEp } from '../src/api/getProgramDetail';
import type { default as _GetProgramsEp } from '../src/api/getPrograms';
import type { default as _GetReconciliationEp } from '../src/api/getReconciliation';
import type { default as _GetReminderTemplatesEp } from '../src/api/getReminderTemplates';
import type { default as _GetRiskAlertsEp } from '../src/api/getRiskAlerts';
import type { default as _GetSystemSettingsEp } from '../src/api/getSystemSettings';
import type { default as _GetTransactionsListEp } from '../src/api/getTransactionsList';
import type { default as _GetWarehouseReceiptsEp } from '../src/api/getWarehouseReceipts';
import type { default as _MarkBackofficeNotificationReadEp } from '../src/api/markBackofficeNotificationRead';
import type { default as _ReconcileBankStatementEp } from '../src/api/reconcileBankStatement';
import type { default as _RecordRepaymentEp } from '../src/api/recordRepayment';
import type { default as _ResendInvitationEp } from '../src/api/resendInvitation';
import type { default as _ReviewOnboardingEp } from '../src/api/reviewOnboarding';
import type { default as _ReviewOnboardingFiEp } from '../src/api/reviewOnboardingFi';
import type { default as _RevokeApiKeyEp } from '../src/api/revokeApiKey';
import type { default as _RunAnomalyScanEp } from '../src/api/runAnomalyScan';
import type { default as _SaveFiPricingEp } from '../src/api/saveFiPricing';
import type { default as _SaveReminderTemplateEp } from '../src/api/saveReminderTemplate';
import type { default as _SeedTestDataEp } from '../src/api/seedTestData';
import type { default as _SendReminderEp } from '../src/api/sendReminder';
import type { default as _ToggleSelfInvoicingEp } from '../src/api/toggleSelfInvoicing';
import type { default as _UpdateBackofficeUserRoleEp } from '../src/api/updateBackofficeUserRole';
import type { default as _UpdateEntityKycEp } from '../src/api/updateEntityKyc';
import type { default as _UpdateInvoiceStatusEp } from '../src/api/updateInvoiceStatus';
import type { default as _UpdatePartnerEp } from '../src/api/updatePartner';
import type { default as _UpdateRiskAlertEp } from '../src/api/updateRiskAlert';
import type { default as _UpdateSystemSettingEp } from '../src/api/updateSystemSetting';
import type { default as _VerifyDocumentEp } from '../src/api/verifyDocument';

type _AiAssistantCfg = typeof _AiAssistantEp;
export type AiAssistantInputType = NonNullable<_AiAssistantCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiAssistantCfg['execute']>[0]['input'];
export type AiAssistantOutputType = Awaited<ReturnType<_AiAssistantCfg['execute']>>;
export const aiAssistant = createStreamingCaller<AiAssistantInputType, AiAssistantOutputType>('aiAssistant');

type _AnalyzeDocumentCfg = typeof _AnalyzeDocumentEp;
export type AnalyzeDocumentInputType = NonNullable<_AnalyzeDocumentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AnalyzeDocumentCfg['execute']>[0]['input'];
export type AnalyzeDocumentOutputType = Awaited<ReturnType<_AnalyzeDocumentCfg['execute']>>;
export const analyzeDocument = createCaller<AnalyzeDocumentInputType, AnalyzeDocumentOutputType>('analyzeDocument');

type _ApproveFinancingRequestCfg = typeof _ApproveFinancingRequestEp;
export type ApproveFinancingRequestInputType = NonNullable<_ApproveFinancingRequestCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ApproveFinancingRequestCfg['execute']>[0]['input'];
export type ApproveFinancingRequestOutputType = Awaited<ReturnType<_ApproveFinancingRequestCfg['execute']>>;
export const approveFinancingRequest = createCaller<ApproveFinancingRequestInputType, ApproveFinancingRequestOutputType>('approveFinancingRequest');

type _ApproveLimitProposalCfg = typeof _ApproveLimitProposalEp;
export type ApproveLimitProposalInputType = NonNullable<_ApproveLimitProposalCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ApproveLimitProposalCfg['execute']>[0]['input'];
export type ApproveLimitProposalOutputType = Awaited<ReturnType<_ApproveLimitProposalCfg['execute']>>;
export const approveLimitProposal = createCaller<ApproveLimitProposalInputType, ApproveLimitProposalOutputType>('approveLimitProposal');

type _AssessFinancingRequestCfg = typeof _AssessFinancingRequestEp;
export type AssessFinancingRequestInputType = NonNullable<_AssessFinancingRequestCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AssessFinancingRequestCfg['execute']>[0]['input'];
export type AssessFinancingRequestOutputType = Awaited<ReturnType<_AssessFinancingRequestCfg['execute']>>;
export const assessFinancingRequest = createCaller<AssessFinancingRequestInputType, AssessFinancingRequestOutputType>('assessFinancingRequest');

type _AssessLimitProposalCfg = typeof _AssessLimitProposalEp;
export type AssessLimitProposalInputType = NonNullable<_AssessLimitProposalCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AssessLimitProposalCfg['execute']>[0]['input'];
export type AssessLimitProposalOutputType = Awaited<ReturnType<_AssessLimitProposalCfg['execute']>>;
export const assessLimitProposal = createCaller<AssessLimitProposalInputType, AssessLimitProposalOutputType>('assessLimitProposal');

type _CalculatePenaltiesCfg = typeof _CalculatePenaltiesEp;
export type CalculatePenaltiesInputType = NonNullable<_CalculatePenaltiesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CalculatePenaltiesCfg['execute']>[0]['input'];
export type CalculatePenaltiesOutputType = Awaited<ReturnType<_CalculatePenaltiesCfg['execute']>>;
export const calculatePenalties = createCaller<CalculatePenaltiesInputType, CalculatePenaltiesOutputType>('calculatePenalties');

type _ComputeCreditScoresCfg = typeof _ComputeCreditScoresEp;
export type ComputeCreditScoresInputType = NonNullable<_ComputeCreditScoresCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ComputeCreditScoresCfg['execute']>[0]['input'];
export type ComputeCreditScoresOutputType = Awaited<ReturnType<_ComputeCreditScoresCfg['execute']>>;
export const computeCreditScores = createCaller<ComputeCreditScoresInputType, ComputeCreditScoresOutputType>('computeCreditScores');

type _CreateInvitationCfg = typeof _CreateInvitationEp;
export type CreateInvitationInputType = NonNullable<_CreateInvitationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateInvitationCfg['execute']>[0]['input'];
export type CreateInvitationOutputType = Awaited<ReturnType<_CreateInvitationCfg['execute']>>;
export const createInvitation = createCaller<CreateInvitationInputType, CreateInvitationOutputType>('createInvitation');

type _CreatePartnerCfg = typeof _CreatePartnerEp;
export type CreatePartnerInputType = NonNullable<_CreatePartnerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreatePartnerCfg['execute']>[0]['input'];
export type CreatePartnerOutputType = Awaited<ReturnType<_CreatePartnerCfg['execute']>>;
export const createPartner = createCaller<CreatePartnerInputType, CreatePartnerOutputType>('createPartner');

type _CreateProgramCfg = typeof _CreateProgramEp;
export type CreateProgramInputType = NonNullable<_CreateProgramCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateProgramCfg['execute']>[0]['input'];
export type CreateProgramOutputType = Awaited<ReturnType<_CreateProgramCfg['execute']>>;
export const createProgram = createCaller<CreateProgramInputType, CreateProgramOutputType>('createProgram');

type _DisburseFinancingRequestCfg = typeof _DisburseFinancingRequestEp;
export type DisburseFinancingRequestInputType = NonNullable<_DisburseFinancingRequestCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DisburseFinancingRequestCfg['execute']>[0]['input'];
export type DisburseFinancingRequestOutputType = Awaited<ReturnType<_DisburseFinancingRequestCfg['execute']>>;
export const disburseFinancingRequest = createCaller<DisburseFinancingRequestInputType, DisburseFinancingRequestOutputType>('disburseFinancingRequest');

type _ExportTableCsvCfg = typeof _ExportTableCsvEp;
export type ExportTableCsvInputType = NonNullable<_ExportTableCsvCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ExportTableCsvCfg['execute']>[0]['input'];
export type ExportTableCsvOutputType = Awaited<ReturnType<_ExportTableCsvCfg['execute']>>;
export const exportTableCsv = createCaller<ExportTableCsvInputType, ExportTableCsvOutputType>('exportTableCsv');

type _GenerateApiKeyCfg = typeof _GenerateApiKeyEp;
export type GenerateApiKeyInputType = NonNullable<_GenerateApiKeyCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GenerateApiKeyCfg['execute']>[0]['input'];
export type GenerateApiKeyOutputType = Awaited<ReturnType<_GenerateApiKeyCfg['execute']>>;
export const generateApiKey = createCaller<GenerateApiKeyInputType, GenerateApiKeyOutputType>('generateApiKey');

type _GenerateBrochurePdfCfg = typeof _GenerateBrochurePdfEp;
export type GenerateBrochurePdfInputType = NonNullable<_GenerateBrochurePdfCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GenerateBrochurePdfCfg['execute']>[0]['input'];
export type GenerateBrochurePdfOutputType = Awaited<ReturnType<_GenerateBrochurePdfCfg['execute']>>;
export const generateBrochurePdf = createCaller<GenerateBrochurePdfInputType, GenerateBrochurePdfOutputType>('generateBrochurePdf');

type _GenerateOfferLetterPdfCfg = typeof _GenerateOfferLetterPdfEp;
export type GenerateOfferLetterPdfInputType = NonNullable<_GenerateOfferLetterPdfCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GenerateOfferLetterPdfCfg['execute']>[0]['input'];
export type GenerateOfferLetterPdfOutputType = Awaited<ReturnType<_GenerateOfferLetterPdfCfg['execute']>>;
export const generateOfferLetterPdf = createCaller<GenerateOfferLetterPdfInputType, GenerateOfferLetterPdfOutputType>('generateOfferLetterPdf');

type _GeneratePitchDeckPdfCfg = typeof _GeneratePitchDeckPdfEp;
export type GeneratePitchDeckPdfInputType = NonNullable<_GeneratePitchDeckPdfCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GeneratePitchDeckPdfCfg['execute']>[0]['input'];
export type GeneratePitchDeckPdfOutputType = Awaited<ReturnType<_GeneratePitchDeckPdfCfg['execute']>>;
export const generatePitchDeckPdf = createCaller<GeneratePitchDeckPdfInputType, GeneratePitchDeckPdfOutputType>('generatePitchDeckPdf');

type _GenerateRemindersCfg = typeof _GenerateRemindersEp;
export type GenerateRemindersInputType = NonNullable<_GenerateRemindersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GenerateRemindersCfg['execute']>[0]['input'];
export type GenerateRemindersOutputType = Awaited<ReturnType<_GenerateRemindersCfg['execute']>>;
export const generateReminders = createCaller<GenerateRemindersInputType, GenerateRemindersOutputType>('generateReminders');

type _GetAssetSchedulesCfg = typeof _GetAssetSchedulesEp;
export type GetAssetSchedulesInputType = NonNullable<_GetAssetSchedulesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetAssetSchedulesCfg['execute']>[0]['input'];
export type GetAssetSchedulesOutputType = Awaited<ReturnType<_GetAssetSchedulesCfg['execute']>>;
export const getAssetSchedules = createCaller<GetAssetSchedulesInputType, GetAssetSchedulesOutputType>('getAssetSchedules');

type _GetBackofficeNotificationsCfg = typeof _GetBackofficeNotificationsEp;
export type GetBackofficeNotificationsInputType = NonNullable<_GetBackofficeNotificationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetBackofficeNotificationsCfg['execute']>[0]['input'];
export type GetBackofficeNotificationsOutputType = Awaited<ReturnType<_GetBackofficeNotificationsCfg['execute']>>;
export const getBackofficeNotifications = createCaller<GetBackofficeNotificationsInputType, GetBackofficeNotificationsOutputType>('getBackofficeNotifications');

type _GetBackofficeUsersCfg = typeof _GetBackofficeUsersEp;
export type GetBackofficeUsersInputType = NonNullable<_GetBackofficeUsersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetBackofficeUsersCfg['execute']>[0]['input'];
export type GetBackofficeUsersOutputType = Awaited<ReturnType<_GetBackofficeUsersCfg['execute']>>;
export const getBackofficeUsers = createCaller<GetBackofficeUsersInputType, GetBackofficeUsersOutputType>('getBackofficeUsers');

type _GetComplianceAlertsCfg = typeof _GetComplianceAlertsEp;
export type GetComplianceAlertsInputType = NonNullable<_GetComplianceAlertsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetComplianceAlertsCfg['execute']>[0]['input'];
export type GetComplianceAlertsOutputType = Awaited<ReturnType<_GetComplianceAlertsCfg['execute']>>;
export const getComplianceAlerts = createCaller<GetComplianceAlertsInputType, GetComplianceAlertsOutputType>('getComplianceAlerts');

type _GetCreditScoresCfg = typeof _GetCreditScoresEp;
export type GetCreditScoresInputType = NonNullable<_GetCreditScoresCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCreditScoresCfg['execute']>[0]['input'];
export type GetCreditScoresOutputType = Awaited<ReturnType<_GetCreditScoresCfg['execute']>>;
export const getCreditScores = createCaller<GetCreditScoresInputType, GetCreditScoresOutputType>('getCreditScores');

type _GetCurrentUserRoleCfg = typeof _GetCurrentUserRoleEp;
export type GetCurrentUserRoleInputType = NonNullable<_GetCurrentUserRoleCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCurrentUserRoleCfg['execute']>[0]['input'];
export type GetCurrentUserRoleOutputType = Awaited<ReturnType<_GetCurrentUserRoleCfg['execute']>>;
export const getCurrentUserRole = createCaller<GetCurrentUserRoleInputType, GetCurrentUserRoleOutputType>('getCurrentUserRole');

type _GetEntitiesForReviewCfg = typeof _GetEntitiesForReviewEp;
export type GetEntitiesForReviewInputType = NonNullable<_GetEntitiesForReviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetEntitiesForReviewCfg['execute']>[0]['input'];
export type GetEntitiesForReviewOutputType = Awaited<ReturnType<_GetEntitiesForReviewCfg['execute']>>;
export const getEntitiesForReview = createCaller<GetEntitiesForReviewInputType, GetEntitiesForReviewOutputType>('getEntitiesForReview');

type _GetEntityBankAccountsCfg = typeof _GetEntityBankAccountsEp;
export type GetEntityBankAccountsInputType = NonNullable<_GetEntityBankAccountsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetEntityBankAccountsCfg['execute']>[0]['input'];
export type GetEntityBankAccountsOutputType = Awaited<ReturnType<_GetEntityBankAccountsCfg['execute']>>;
export const getEntityBankAccounts = createCaller<GetEntityBankAccountsInputType, GetEntityBankAccountsOutputType>('getEntityBankAccounts');

type _GetEntityDetailCfg = typeof _GetEntityDetailEp;
export type GetEntityDetailInputType = NonNullable<_GetEntityDetailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetEntityDetailCfg['execute']>[0]['input'];
export type GetEntityDetailOutputType = Awaited<ReturnType<_GetEntityDetailCfg['execute']>>;
export const getEntityDetail = createCaller<GetEntityDetailInputType, GetEntityDetailOutputType>('getEntityDetail');

type _GetFiLedgerCfg = typeof _GetFiLedgerEp;
export type GetFiLedgerInputType = NonNullable<_GetFiLedgerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetFiLedgerCfg['execute']>[0]['input'];
export type GetFiLedgerOutputType = Awaited<ReturnType<_GetFiLedgerCfg['execute']>>;
export const getFiLedger = createCaller<GetFiLedgerInputType, GetFiLedgerOutputType>('getFiLedger');

type _GetFiLoansCfg = typeof _GetFiLoansEp;
export type GetFiLoansInputType = NonNullable<_GetFiLoansCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetFiLoansCfg['execute']>[0]['input'];
export type GetFiLoansOutputType = Awaited<ReturnType<_GetFiLoansCfg['execute']>>;
export const getFiLoans = createCaller<GetFiLoansInputType, GetFiLoansOutputType>('getFiLoans');

type _GetFiScreeningQueueCfg = typeof _GetFiScreeningQueueEp;
export type GetFiScreeningQueueInputType = NonNullable<_GetFiScreeningQueueCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetFiScreeningQueueCfg['execute']>[0]['input'];
export type GetFiScreeningQueueOutputType = Awaited<ReturnType<_GetFiScreeningQueueCfg['execute']>>;
export const getFiScreeningQueue = createCaller<GetFiScreeningQueueInputType, GetFiScreeningQueueOutputType>('getFiScreeningQueue');

type _GetFinancialInstitutionsCfg = typeof _GetFinancialInstitutionsEp;
export type GetFinancialInstitutionsInputType = NonNullable<_GetFinancialInstitutionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetFinancialInstitutionsCfg['execute']>[0]['input'];
export type GetFinancialInstitutionsOutputType = Awaited<ReturnType<_GetFinancialInstitutionsCfg['execute']>>;
export const getFinancialInstitutions = createCaller<GetFinancialInstitutionsInputType, GetFinancialInstitutionsOutputType>('getFinancialInstitutions');

type _GetFinancingRequestDetailCfg = typeof _GetFinancingRequestDetailEp;
export type GetFinancingRequestDetailInputType = NonNullable<_GetFinancingRequestDetailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetFinancingRequestDetailCfg['execute']>[0]['input'];
export type GetFinancingRequestDetailOutputType = Awaited<ReturnType<_GetFinancingRequestDetailCfg['execute']>>;
export const getFinancingRequestDetail = createCaller<GetFinancingRequestDetailInputType, GetFinancingRequestDetailOutputType>('getFinancingRequestDetail');

type _GetFinancingRequestsListCfg = typeof _GetFinancingRequestsListEp;
export type GetFinancingRequestsListInputType = NonNullable<_GetFinancingRequestsListCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetFinancingRequestsListCfg['execute']>[0]['input'];
export type GetFinancingRequestsListOutputType = Awaited<ReturnType<_GetFinancingRequestsListCfg['execute']>>;
export const getFinancingRequestsList = createCaller<GetFinancingRequestsListInputType, GetFinancingRequestsListOutputType>('getFinancingRequestsList');

type _GetInvitationsCfg = typeof _GetInvitationsEp;
export type GetInvitationsInputType = NonNullable<_GetInvitationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetInvitationsCfg['execute']>[0]['input'];
export type GetInvitationsOutputType = Awaited<ReturnType<_GetInvitationsCfg['execute']>>;
export const getInvitations = createCaller<GetInvitationsInputType, GetInvitationsOutputType>('getInvitations');

type _GetInvoiceDetailCfg = typeof _GetInvoiceDetailEp;
export type GetInvoiceDetailInputType = NonNullable<_GetInvoiceDetailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetInvoiceDetailCfg['execute']>[0]['input'];
export type GetInvoiceDetailOutputType = Awaited<ReturnType<_GetInvoiceDetailCfg['execute']>>;
export const getInvoiceDetail = createCaller<GetInvoiceDetailInputType, GetInvoiceDetailOutputType>('getInvoiceDetail');

type _GetInvoicesListCfg = typeof _GetInvoicesListEp;
export type GetInvoicesListInputType = NonNullable<_GetInvoicesListCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetInvoicesListCfg['execute']>[0]['input'];
export type GetInvoicesListOutputType = Awaited<ReturnType<_GetInvoicesListCfg['execute']>>;
export const getInvoicesList = createCaller<GetInvoicesListInputType, GetInvoicesListOutputType>('getInvoicesList');

type _GetLimitProposalsListCfg = typeof _GetLimitProposalsListEp;
export type GetLimitProposalsListInputType = NonNullable<_GetLimitProposalsListCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetLimitProposalsListCfg['execute']>[0]['input'];
export type GetLimitProposalsListOutputType = Awaited<ReturnType<_GetLimitProposalsListCfg['execute']>>;
export const getLimitProposalsList = createCaller<GetLimitProposalsListInputType, GetLimitProposalsListOutputType>('getLimitProposalsList');

type _GetLoanDetailCfg = typeof _GetLoanDetailEp;
export type GetLoanDetailInputType = NonNullable<_GetLoanDetailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetLoanDetailCfg['execute']>[0]['input'];
export type GetLoanDetailOutputType = Awaited<ReturnType<_GetLoanDetailCfg['execute']>>;
export const getLoanDetail = createCaller<GetLoanDetailInputType, GetLoanDetailOutputType>('getLoanDetail');

type _GetOfferLettersListCfg = typeof _GetOfferLettersListEp;
export type GetOfferLettersListInputType = NonNullable<_GetOfferLettersListCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetOfferLettersListCfg['execute']>[0]['input'];
export type GetOfferLettersListOutputType = Awaited<ReturnType<_GetOfferLettersListCfg['execute']>>;
export const getOfferLettersList = createCaller<GetOfferLettersListInputType, GetOfferLettersListOutputType>('getOfferLettersList');

type _GetOnboardingDetailCfg = typeof _GetOnboardingDetailEp;
export type GetOnboardingDetailInputType = NonNullable<_GetOnboardingDetailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetOnboardingDetailCfg['execute']>[0]['input'];
export type GetOnboardingDetailOutputType = Awaited<ReturnType<_GetOnboardingDetailCfg['execute']>>;
export const getOnboardingDetail = createCaller<GetOnboardingDetailInputType, GetOnboardingDetailOutputType>('getOnboardingDetail');

type _GetOnboardingsListCfg = typeof _GetOnboardingsListEp;
export type GetOnboardingsListInputType = NonNullable<_GetOnboardingsListCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetOnboardingsListCfg['execute']>[0]['input'];
export type GetOnboardingsListOutputType = Awaited<ReturnType<_GetOnboardingsListCfg['execute']>>;
export const getOnboardingsList = createCaller<GetOnboardingsListInputType, GetOnboardingsListOutputType>('getOnboardingsList');

type _GetOverdueLoansCfg = typeof _GetOverdueLoansEp;
export type GetOverdueLoansInputType = NonNullable<_GetOverdueLoansCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetOverdueLoansCfg['execute']>[0]['input'];
export type GetOverdueLoansOutputType = Awaited<ReturnType<_GetOverdueLoansCfg['execute']>>;
export const getOverdueLoans = createCaller<GetOverdueLoansInputType, GetOverdueLoansOutputType>('getOverdueLoans');

type _GetOverviewCfg = typeof _GetOverviewEp;
export type GetOverviewInputType = NonNullable<_GetOverviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetOverviewCfg['execute']>[0]['input'];
export type GetOverviewOutputType = Awaited<ReturnType<_GetOverviewCfg['execute']>>;
export const getOverview = createCaller<GetOverviewInputType, GetOverviewOutputType>('getOverview');

type _GetPartnerDetailCfg = typeof _GetPartnerDetailEp;
export type GetPartnerDetailInputType = NonNullable<_GetPartnerDetailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPartnerDetailCfg['execute']>[0]['input'];
export type GetPartnerDetailOutputType = Awaited<ReturnType<_GetPartnerDetailCfg['execute']>>;
export const getPartnerDetail = createCaller<GetPartnerDetailInputType, GetPartnerDetailOutputType>('getPartnerDetail');

type _GetPartnerEntitiesCfg = typeof _GetPartnerEntitiesEp;
export type GetPartnerEntitiesInputType = NonNullable<_GetPartnerEntitiesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPartnerEntitiesCfg['execute']>[0]['input'];
export type GetPartnerEntitiesOutputType = Awaited<ReturnType<_GetPartnerEntitiesCfg['execute']>>;
export const getPartnerEntities = createCaller<GetPartnerEntitiesInputType, GetPartnerEntitiesOutputType>('getPartnerEntities');

type _GetPartnerFinancingCfg = typeof _GetPartnerFinancingEp;
export type GetPartnerFinancingInputType = NonNullable<_GetPartnerFinancingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPartnerFinancingCfg['execute']>[0]['input'];
export type GetPartnerFinancingOutputType = Awaited<ReturnType<_GetPartnerFinancingCfg['execute']>>;
export const getPartnerFinancing = createCaller<GetPartnerFinancingInputType, GetPartnerFinancingOutputType>('getPartnerFinancing');

type _GetPartnerInvoicesCfg = typeof _GetPartnerInvoicesEp;
export type GetPartnerInvoicesInputType = NonNullable<_GetPartnerInvoicesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPartnerInvoicesCfg['execute']>[0]['input'];
export type GetPartnerInvoicesOutputType = Awaited<ReturnType<_GetPartnerInvoicesCfg['execute']>>;
export const getPartnerInvoices = createCaller<GetPartnerInvoicesInputType, GetPartnerInvoicesOutputType>('getPartnerInvoices');

type _GetPartnerLoansCfg = typeof _GetPartnerLoansEp;
export type GetPartnerLoansInputType = NonNullable<_GetPartnerLoansCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPartnerLoansCfg['execute']>[0]['input'];
export type GetPartnerLoansOutputType = Awaited<ReturnType<_GetPartnerLoansCfg['execute']>>;
export const getPartnerLoans = createCaller<GetPartnerLoansInputType, GetPartnerLoansOutputType>('getPartnerLoans');

type _GetPartnerOverviewCfg = typeof _GetPartnerOverviewEp;
export type GetPartnerOverviewInputType = NonNullable<_GetPartnerOverviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPartnerOverviewCfg['execute']>[0]['input'];
export type GetPartnerOverviewOutputType = Awaited<ReturnType<_GetPartnerOverviewCfg['execute']>>;
export const getPartnerOverview = createCaller<GetPartnerOverviewInputType, GetPartnerOverviewOutputType>('getPartnerOverview');

type _GetPartnerProgramsCfg = typeof _GetPartnerProgramsEp;
export type GetPartnerProgramsInputType = NonNullable<_GetPartnerProgramsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPartnerProgramsCfg['execute']>[0]['input'];
export type GetPartnerProgramsOutputType = Awaited<ReturnType<_GetPartnerProgramsCfg['execute']>>;
export const getPartnerPrograms = createCaller<GetPartnerProgramsInputType, GetPartnerProgramsOutputType>('getPartnerPrograms');

type _GetPartnerTransactionsCfg = typeof _GetPartnerTransactionsEp;
export type GetPartnerTransactionsInputType = NonNullable<_GetPartnerTransactionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPartnerTransactionsCfg['execute']>[0]['input'];
export type GetPartnerTransactionsOutputType = Awaited<ReturnType<_GetPartnerTransactionsCfg['execute']>>;
export const getPartnerTransactions = createCaller<GetPartnerTransactionsInputType, GetPartnerTransactionsOutputType>('getPartnerTransactions');

type _GetPartnersListCfg = typeof _GetPartnersListEp;
export type GetPartnersListInputType = NonNullable<_GetPartnersListCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPartnersListCfg['execute']>[0]['input'];
export type GetPartnersListOutputType = Awaited<ReturnType<_GetPartnersListCfg['execute']>>;
export const getPartnersList = createCaller<GetPartnersListInputType, GetPartnersListOutputType>('getPartnersList');

type _GetProgramDetailCfg = typeof _GetProgramDetailEp;
export type GetProgramDetailInputType = NonNullable<_GetProgramDetailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetProgramDetailCfg['execute']>[0]['input'];
export type GetProgramDetailOutputType = Awaited<ReturnType<_GetProgramDetailCfg['execute']>>;
export const getProgramDetail = createCaller<GetProgramDetailInputType, GetProgramDetailOutputType>('getProgramDetail');

type _GetProgramsCfg = typeof _GetProgramsEp;
export type GetProgramsInputType = NonNullable<_GetProgramsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetProgramsCfg['execute']>[0]['input'];
export type GetProgramsOutputType = Awaited<ReturnType<_GetProgramsCfg['execute']>>;
export const getPrograms = createCaller<GetProgramsInputType, GetProgramsOutputType>('getPrograms');

type _GetReconciliationCfg = typeof _GetReconciliationEp;
export type GetReconciliationInputType = NonNullable<_GetReconciliationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetReconciliationCfg['execute']>[0]['input'];
export type GetReconciliationOutputType = Awaited<ReturnType<_GetReconciliationCfg['execute']>>;
export const getReconciliation = createCaller<GetReconciliationInputType, GetReconciliationOutputType>('getReconciliation');

type _GetReminderTemplatesCfg = typeof _GetReminderTemplatesEp;
export type GetReminderTemplatesInputType = NonNullable<_GetReminderTemplatesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetReminderTemplatesCfg['execute']>[0]['input'];
export type GetReminderTemplatesOutputType = Awaited<ReturnType<_GetReminderTemplatesCfg['execute']>>;
export const getReminderTemplates = createCaller<GetReminderTemplatesInputType, GetReminderTemplatesOutputType>('getReminderTemplates');

type _GetRiskAlertsCfg = typeof _GetRiskAlertsEp;
export type GetRiskAlertsInputType = NonNullable<_GetRiskAlertsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetRiskAlertsCfg['execute']>[0]['input'];
export type GetRiskAlertsOutputType = Awaited<ReturnType<_GetRiskAlertsCfg['execute']>>;
export const getRiskAlerts = createCaller<GetRiskAlertsInputType, GetRiskAlertsOutputType>('getRiskAlerts');

type _GetSystemSettingsCfg = typeof _GetSystemSettingsEp;
export type GetSystemSettingsInputType = NonNullable<_GetSystemSettingsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetSystemSettingsCfg['execute']>[0]['input'];
export type GetSystemSettingsOutputType = Awaited<ReturnType<_GetSystemSettingsCfg['execute']>>;
export const getSystemSettings = createCaller<GetSystemSettingsInputType, GetSystemSettingsOutputType>('getSystemSettings');

type _GetTransactionsListCfg = typeof _GetTransactionsListEp;
export type GetTransactionsListInputType = NonNullable<_GetTransactionsListCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetTransactionsListCfg['execute']>[0]['input'];
export type GetTransactionsListOutputType = Awaited<ReturnType<_GetTransactionsListCfg['execute']>>;
export const getTransactionsList = createCaller<GetTransactionsListInputType, GetTransactionsListOutputType>('getTransactionsList');

type _GetWarehouseReceiptsCfg = typeof _GetWarehouseReceiptsEp;
export type GetWarehouseReceiptsInputType = NonNullable<_GetWarehouseReceiptsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetWarehouseReceiptsCfg['execute']>[0]['input'];
export type GetWarehouseReceiptsOutputType = Awaited<ReturnType<_GetWarehouseReceiptsCfg['execute']>>;
export const getWarehouseReceipts = createCaller<GetWarehouseReceiptsInputType, GetWarehouseReceiptsOutputType>('getWarehouseReceipts');

type _MarkBackofficeNotificationReadCfg = typeof _MarkBackofficeNotificationReadEp;
export type MarkBackofficeNotificationReadInputType = NonNullable<_MarkBackofficeNotificationReadCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_MarkBackofficeNotificationReadCfg['execute']>[0]['input'];
export type MarkBackofficeNotificationReadOutputType = Awaited<ReturnType<_MarkBackofficeNotificationReadCfg['execute']>>;
export const markBackofficeNotificationRead = createCaller<MarkBackofficeNotificationReadInputType, MarkBackofficeNotificationReadOutputType>('markBackofficeNotificationRead');

type _ReconcileBankStatementCfg = typeof _ReconcileBankStatementEp;
export type ReconcileBankStatementInputType = NonNullable<_ReconcileBankStatementCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReconcileBankStatementCfg['execute']>[0]['input'];
export type ReconcileBankStatementOutputType = Awaited<ReturnType<_ReconcileBankStatementCfg['execute']>>;
export const reconcileBankStatement = createCaller<ReconcileBankStatementInputType, ReconcileBankStatementOutputType>('reconcileBankStatement');

type _RecordRepaymentCfg = typeof _RecordRepaymentEp;
export type RecordRepaymentInputType = NonNullable<_RecordRepaymentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RecordRepaymentCfg['execute']>[0]['input'];
export type RecordRepaymentOutputType = Awaited<ReturnType<_RecordRepaymentCfg['execute']>>;
export const recordRepayment = createCaller<RecordRepaymentInputType, RecordRepaymentOutputType>('recordRepayment');

type _ResendInvitationCfg = typeof _ResendInvitationEp;
export type ResendInvitationInputType = NonNullable<_ResendInvitationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ResendInvitationCfg['execute']>[0]['input'];
export type ResendInvitationOutputType = Awaited<ReturnType<_ResendInvitationCfg['execute']>>;
export const resendInvitation = createCaller<ResendInvitationInputType, ResendInvitationOutputType>('resendInvitation');

type _ReviewOnboardingCfg = typeof _ReviewOnboardingEp;
export type ReviewOnboardingInputType = NonNullable<_ReviewOnboardingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReviewOnboardingCfg['execute']>[0]['input'];
export type ReviewOnboardingOutputType = Awaited<ReturnType<_ReviewOnboardingCfg['execute']>>;
export const reviewOnboarding = createCaller<ReviewOnboardingInputType, ReviewOnboardingOutputType>('reviewOnboarding');

type _ReviewOnboardingFiCfg = typeof _ReviewOnboardingFiEp;
export type ReviewOnboardingFiInputType = NonNullable<_ReviewOnboardingFiCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReviewOnboardingFiCfg['execute']>[0]['input'];
export type ReviewOnboardingFiOutputType = Awaited<ReturnType<_ReviewOnboardingFiCfg['execute']>>;
export const reviewOnboardingFi = createCaller<ReviewOnboardingFiInputType, ReviewOnboardingFiOutputType>('reviewOnboardingFi');

type _RevokeApiKeyCfg = typeof _RevokeApiKeyEp;
export type RevokeApiKeyInputType = NonNullable<_RevokeApiKeyCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RevokeApiKeyCfg['execute']>[0]['input'];
export type RevokeApiKeyOutputType = Awaited<ReturnType<_RevokeApiKeyCfg['execute']>>;
export const revokeApiKey = createCaller<RevokeApiKeyInputType, RevokeApiKeyOutputType>('revokeApiKey');

type _RunAnomalyScanCfg = typeof _RunAnomalyScanEp;
export type RunAnomalyScanInputType = NonNullable<_RunAnomalyScanCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RunAnomalyScanCfg['execute']>[0]['input'];
export type RunAnomalyScanOutputType = Awaited<ReturnType<_RunAnomalyScanCfg['execute']>>;
export const runAnomalyScan = createCaller<RunAnomalyScanInputType, RunAnomalyScanOutputType>('runAnomalyScan');

type _SaveFiPricingCfg = typeof _SaveFiPricingEp;
export type SaveFiPricingInputType = NonNullable<_SaveFiPricingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveFiPricingCfg['execute']>[0]['input'];
export type SaveFiPricingOutputType = Awaited<ReturnType<_SaveFiPricingCfg['execute']>>;
export const saveFiPricing = createCaller<SaveFiPricingInputType, SaveFiPricingOutputType>('saveFiPricing');

type _SaveReminderTemplateCfg = typeof _SaveReminderTemplateEp;
export type SaveReminderTemplateInputType = NonNullable<_SaveReminderTemplateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveReminderTemplateCfg['execute']>[0]['input'];
export type SaveReminderTemplateOutputType = Awaited<ReturnType<_SaveReminderTemplateCfg['execute']>>;
export const saveReminderTemplate = createCaller<SaveReminderTemplateInputType, SaveReminderTemplateOutputType>('saveReminderTemplate');

type _SeedTestDataCfg = typeof _SeedTestDataEp;
export type SeedTestDataInputType = NonNullable<_SeedTestDataCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SeedTestDataCfg['execute']>[0]['input'];
export type SeedTestDataOutputType = Awaited<ReturnType<_SeedTestDataCfg['execute']>>;
export const seedTestData = createCaller<SeedTestDataInputType, SeedTestDataOutputType>('seedTestData');

type _SendReminderCfg = typeof _SendReminderEp;
export type SendReminderInputType = NonNullable<_SendReminderCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendReminderCfg['execute']>[0]['input'];
export type SendReminderOutputType = Awaited<ReturnType<_SendReminderCfg['execute']>>;
export const sendReminder = createCaller<SendReminderInputType, SendReminderOutputType>('sendReminder');

type _ToggleSelfInvoicingCfg = typeof _ToggleSelfInvoicingEp;
export type ToggleSelfInvoicingInputType = NonNullable<_ToggleSelfInvoicingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ToggleSelfInvoicingCfg['execute']>[0]['input'];
export type ToggleSelfInvoicingOutputType = Awaited<ReturnType<_ToggleSelfInvoicingCfg['execute']>>;
export const toggleSelfInvoicing = createCaller<ToggleSelfInvoicingInputType, ToggleSelfInvoicingOutputType>('toggleSelfInvoicing');

type _UpdateBackofficeUserRoleCfg = typeof _UpdateBackofficeUserRoleEp;
export type UpdateBackofficeUserRoleInputType = NonNullable<_UpdateBackofficeUserRoleCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateBackofficeUserRoleCfg['execute']>[0]['input'];
export type UpdateBackofficeUserRoleOutputType = Awaited<ReturnType<_UpdateBackofficeUserRoleCfg['execute']>>;
export const updateBackofficeUserRole = createCaller<UpdateBackofficeUserRoleInputType, UpdateBackofficeUserRoleOutputType>('updateBackofficeUserRole');

type _UpdateEntityKycCfg = typeof _UpdateEntityKycEp;
export type UpdateEntityKycInputType = NonNullable<_UpdateEntityKycCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateEntityKycCfg['execute']>[0]['input'];
export type UpdateEntityKycOutputType = Awaited<ReturnType<_UpdateEntityKycCfg['execute']>>;
export const updateEntityKyc = createCaller<UpdateEntityKycInputType, UpdateEntityKycOutputType>('updateEntityKyc');

type _UpdateInvoiceStatusCfg = typeof _UpdateInvoiceStatusEp;
export type UpdateInvoiceStatusInputType = NonNullable<_UpdateInvoiceStatusCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateInvoiceStatusCfg['execute']>[0]['input'];
export type UpdateInvoiceStatusOutputType = Awaited<ReturnType<_UpdateInvoiceStatusCfg['execute']>>;
export const updateInvoiceStatus = createCaller<UpdateInvoiceStatusInputType, UpdateInvoiceStatusOutputType>('updateInvoiceStatus');

type _UpdatePartnerCfg = typeof _UpdatePartnerEp;
export type UpdatePartnerInputType = NonNullable<_UpdatePartnerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdatePartnerCfg['execute']>[0]['input'];
export type UpdatePartnerOutputType = Awaited<ReturnType<_UpdatePartnerCfg['execute']>>;
export const updatePartner = createCaller<UpdatePartnerInputType, UpdatePartnerOutputType>('updatePartner');

type _UpdateRiskAlertCfg = typeof _UpdateRiskAlertEp;
export type UpdateRiskAlertInputType = NonNullable<_UpdateRiskAlertCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateRiskAlertCfg['execute']>[0]['input'];
export type UpdateRiskAlertOutputType = Awaited<ReturnType<_UpdateRiskAlertCfg['execute']>>;
export const updateRiskAlert = createCaller<UpdateRiskAlertInputType, UpdateRiskAlertOutputType>('updateRiskAlert');

type _UpdateSystemSettingCfg = typeof _UpdateSystemSettingEp;
export type UpdateSystemSettingInputType = NonNullable<_UpdateSystemSettingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateSystemSettingCfg['execute']>[0]['input'];
export type UpdateSystemSettingOutputType = Awaited<ReturnType<_UpdateSystemSettingCfg['execute']>>;
export const updateSystemSetting = createCaller<UpdateSystemSettingInputType, UpdateSystemSettingOutputType>('updateSystemSetting');

type _VerifyDocumentCfg = typeof _VerifyDocumentEp;
export type VerifyDocumentInputType = NonNullable<_VerifyDocumentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_VerifyDocumentCfg['execute']>[0]['input'];
export type VerifyDocumentOutputType = Awaited<ReturnType<_VerifyDocumentCfg['execute']>>;
export const verifyDocument = createCaller<VerifyDocumentInputType, VerifyDocumentOutputType>('verifyDocument');


export const api = {
  aiAssistant,
  analyzeDocument,
  approveFinancingRequest,
  approveLimitProposal,
  assessFinancingRequest,
  assessLimitProposal,
  calculatePenalties,
  computeCreditScores,
  createInvitation,
  createPartner,
  createProgram,
  disburseFinancingRequest,
  exportTableCsv,
  generateApiKey,
  generateBrochurePdf,
  generateOfferLetterPdf,
  generatePitchDeckPdf,
  generateReminders,
  getAssetSchedules,
  getBackofficeNotifications,
  getBackofficeUsers,
  getComplianceAlerts,
  getCreditScores,
  getCurrentUserRole,
  getEntitiesForReview,
  getEntityBankAccounts,
  getEntityDetail,
  getFiLedger,
  getFiLoans,
  getFiScreeningQueue,
  getFinancialInstitutions,
  getFinancingRequestDetail,
  getFinancingRequestsList,
  getInvitations,
  getInvoiceDetail,
  getInvoicesList,
  getLimitProposalsList,
  getLoanDetail,
  getOfferLettersList,
  getOnboardingDetail,
  getOnboardingsList,
  getOverdueLoans,
  getOverview,
  getPartnerDetail,
  getPartnerEntities,
  getPartnerFinancing,
  getPartnerInvoices,
  getPartnerLoans,
  getPartnerOverview,
  getPartnerPrograms,
  getPartnerTransactions,
  getPartnersList,
  getProgramDetail,
  getPrograms,
  getReconciliation,
  getReminderTemplates,
  getRiskAlerts,
  getSystemSettings,
  getTransactionsList,
  getWarehouseReceipts,
  markBackofficeNotificationRead,
  reconcileBankStatement,
  recordRepayment,
  resendInvitation,
  reviewOnboarding,
  reviewOnboardingFi,
  revokeApiKey,
  runAnomalyScan,
  saveFiPricing,
  saveReminderTemplate,
  seedTestData,
  sendReminder,
  toggleSelfInvoicing,
  updateBackofficeUserRole,
  updateEntityKyc,
  updateInvoiceStatus,
  updatePartner,
  updateRiskAlert,
  updateSystemSetting,
  verifyDocument,
};
