// Auto-generated by zitejs generate. Do not edit manually.
//
// Usage in endpoint files (src/api/*.ts):
//   import { zite } from "zitejs/db";
//
// Always use "zitejs/db" — never use relative paths like "../../.zite/db".
// The tsconfig aliases resolve zitejs/* imports to the correct .zite/ files.
//
// Table client methods (all take a single params object):
//   .findAll({ filters?, sort?, offset?, limit?, fields? }) → { records: T[], hasMore: boolean }
//     filters: { fieldName: value } for equality, or { fieldName: { <op>: value } }
//     operators: contains, not, in, notIn, lt, lte, gt, gte
//       `not: null` means "is set". An empty `in: []` matches nothing; an
//       empty `notIn: []` applies no filter.
//     sort is currently IGNORED here — it is stripped before the request.
//       (it does work on zite.auth.findAllUsers). Order in SQL instead.
//     limit defaults to 500, max 2000; offset is a row count (a number)
//   .findOne({ id?, filters?, fields? }) → T | undefined
//   .create({ record }) → T
//   .update({ id, record }) → { id: string, fields: Partial<T> }
//   .delete({ id }) → { success: true, id: string }
//   .bulkCreate({ records, matchOn? }) → { success: boolean, records: T[] }
//     up to 100 records per call; matchOn upserts on those fields
//
// Reading these types:
//   SDK names are stable identifiers — they do NOT change when a table or field is
//   renamed. Each carries its current user-facing name in quotes (// "Task Name").
//   Where the two differ the field was renamed, and the quoted name is what it means
//   now — treat it as the source of truth.
//   Values are RAW: dates are ISO strings, durations are seconds. Format them for
//   display yourself, following the display config in each field's comment.
//   PERCENT fields are stored as decimals — 0.5 is 50%, 1.0 is 100%.
//   LINKED RECORD fields hold UUID record ids from findOne/findAll — never invent one.
//   Computed and system-managed fields (formula, rollup, lookup, autonumber,
//   created/updated timestamps and more) are absent from the *Input types —
//   a write to one is rejected or silently dropped.
//
// Zite auth users:
//   zite.auth.findAllUsers({ appIds?, filter?, filters?, sort?, limit?, offset? })
//     Supports the same filter, sort, and pagination options as table .findAll()
//     appIds restricts results to users belonging to any listed app
//   zite.auth.updateUserProfile(userId, { firstName?, lastName?, image? })
//   User email addresses cannot be updated through this API
//
// Raw SQL (read-only SELECTs for aggregates, joins, multi-table queries):
//   zite.sql({ query: "SELECT ...", params?: [...] })
//     → { rows: Record<string, unknown>[], columns, rowCount, truncated }
//     Capped at 2000 rows — `truncated: true` means there were more, so paginate in
//     SQL rather than assuming you got everything. Queries time out after 10s.
//     columns[].name is the SDK name; columns[].originalName is the underlying
//     database column (or your own SQL alias).
//
// SQL guidelines:
//   - Use SDK names for tables (PascalCase) and fields (camelCase)
//   - ALWAYS double-quote every identifier: FROM "Orders", WHERE "status" = $1
//   - Use params array for user input ($1, $2, ...): never interpolate into SQL
//   - Auth users are available as "ziteUsers" with id, name, email, firstName, lastName, and image
//   - Soft-deleted rows are excluded automatically — no WHERE deleted_at IS NULL
//   - SELECT only — use .create/.update/.delete for writes
//   - Load the "zite:sql" skill for full SQL reference (formulas, lookups, etc.)
//
// Link tables for zite.sql() JOINs (use these exact names):
//   "InvitationsPrograms" — columns: "invitationsId", "programsId" (joins "Invitations" and "Programs")
//   "EntitiesInvitations" — columns: "entitiesId", "invitationsId" (joins "Entities" and "Invitations")
//   "ApiPartnersBackofficeUsers" — columns: "apiPartnersId", "backofficeUsersId" (joins "API Partners" and "Backoffice Users")
//   "ApiPartnersEntities" — columns: "apiPartnersId", "entitiesId" (joins "API Partners" and "Entities")
//   "EntitiesPrograms" — columns: "entitiesId", "programsId" (joins "Entities" and "Programs")
//   "ApiPartnersPrograms" — columns: "apiPartnersId", "programsId" (joins "API Partners" and "Programs")
//   "EntitiesLoans" — columns: "entitiesId", "loansId" (joins "Entities" and "Loans")
//   "LoansPrograms" — columns: "loansId", "programsId" (joins "Loans" and "Programs")
//   "LoansTransactions" — columns: "loansId", "transactionsId" (joins "Loans" and "Transactions")
//   "EntitiesOnboardings" — columns: "entitiesId", "onboardingsId" (joins "Entities" and "Onboardings")
//   "OnboardingsPrograms" — columns: "onboardingsId", "programsId" (joins "Onboardings" and "Programs")
//   "InvitationsOnboardings" — columns: "invitationsId", "onboardingsId" (joins "Invitations" and "Onboardings")
//   "OnboardingDocumentsOnboardings" — columns: "onboardingDocumentsId", "onboardingsId" (joins "Onboarding Documents" and "Onboardings")
//   "EntitiesEntityOwners" — columns: "entitiesId", "entityOwnersId" (joins "Entities" and "Entity Owners")
//   "EntitiesEntityOperators" — columns: "entitiesId", "entityOperatorsId" (joins "Entities" and "Entity Operators")
//   "EntitiesLimitProposals" — columns: "entitiesId", "limitProposalsId" (joins "Entities" and "Limit Proposals")
//   "LimitProposalsPrograms" — columns: "limitProposalsId", "programsId" (joins "Limit Proposals" and "Programs")
//   "LimitProposalsOnboardings" — columns: "limitProposalsId", "onboardingsId" (joins "Limit Proposals" and "Onboardings")
//   "EntitiesInvoices" — columns: "entitiesId", "invoicesId" (joins "Entities" and "Invoices")
//   "InvoicesPrograms" — columns: "invoicesId", "programsId" (joins "Invoices" and "Programs")
//   "EntitiesFinancingRequests" — columns: "entitiesId", "financingRequestsId" (joins "Entities" and "Financing Requests")
//   "FinancingRequestsPrograms" — columns: "financingRequestsId", "programsId" (joins "Financing Requests" and "Programs")
//   "FinancingRequestsInvoices" — columns: "financingRequestsId", "invoicesId" (joins "Financing Requests" and "Invoices")
//   "FinancingRequestsLoans" — columns: "financingRequestsId", "loansId" (joins "Financing Requests" and "Loans")
//   "FiProgramPricingFinancingRequests" — columns: "fiProgramPricingId", "financingRequestsId" (joins "FI Program Pricing" and "Financing Requests")
//   "EntitiesOfferLetters" — columns: "entitiesId", "offerLettersId" (joins "Entities" and "Offer Letters")
//   "OfferLettersOnboardings" — columns: "offerLettersId", "onboardingsId" (joins "Offer Letters" and "Onboardings")
//   "OfferLettersPrograms" — columns: "offerLettersId", "programsId" (joins "Offer Letters" and "Programs")
//   "FiProgramPricingFinancialInstitutions" — columns: "fiProgramPricingId", "financialInstitutionsId" (joins "FI Program Pricing" and "Financial Institutions")
//   "FiProgramPricingPrograms" — columns: "fiProgramPricingId", "programsId" (joins "FI Program Pricing" and "Programs")
//   "EntitiesJournalEntries" — columns: "entitiesId", "journalEntriesId" (joins "Entities" and "Journal Entries")
//   "JournalEntriesPrograms" — columns: "journalEntriesId", "programsId" (joins "Journal Entries" and "Programs")
//   "FinancingRequestsJournalEntries" — columns: "financingRequestsId", "journalEntriesId" (joins "Financing Requests" and "Journal Entries")
//   "JournalEntriesLoans" — columns: "journalEntriesId", "loansId" (joins "Journal Entries" and "Loans")
//   "JournalEntriesJournalLines" — columns: "journalEntriesId", "journalLinesId" (joins "Journal Entries" and "Journal Lines")
//   "GlAccountsJournalLines" — columns: "glAccountsId", "journalLinesId" (joins "GL Accounts" and "Journal Lines")
//   "CreditScoresEntities" — columns: "creditScoresId", "entitiesId" (joins "Credit Scores" and "Entities")
//   "EntitiesRiskAlerts" — columns: "entitiesId", "riskAlertsId" (joins "Entities" and "Risk Alerts")
//   "ProgramsRiskAlerts" — columns: "programsId", "riskAlertsId" (joins "Programs" and "Risk Alerts")
//   "BankAccountsEntities" — columns: "bankAccountsId", "entitiesId" (joins "Bank Accounts" and "Entities")
//   "AssetSchedulesEntities" — columns: "assetSchedulesId", "entitiesId" (joins "Asset Schedules" and "Entities")
//   "AssetSchedulesPrograms" — columns: "assetSchedulesId", "programsId" (joins "Asset Schedules" and "Programs")
//   "AssetSchedulesLoans" — columns: "assetSchedulesId", "loansId" (joins "Asset Schedules" and "Loans")
//   "EntitiesWarehouseReceipts" — columns: "entitiesId", "warehouseReceiptsId" (joins "Entities" and "Warehouse Receipts")
//   "ProgramsWarehouseReceipts" — columns: "programsId", "warehouseReceiptsId" (joins "Programs" and "Warehouse Receipts")
//   "LoansWarehouseReceipts" — columns: "loansId", "warehouseReceiptsId" (joins "Loans" and "Warehouse Receipts")
//   "ApiKeysApiPartners" — columns: "apiKeysId", "apiPartnersId" (joins "API Keys" and "API Partners")
//   "ApiActivityLogApiPartners" — columns: "apiActivityLogId", "apiPartnersId" (joins "API Activity Log" and "API Partners")
//   "ApiActivityLogApiKeys" — columns: "apiActivityLogId", "apiKeysId" (joins "API Activity Log" and "API Keys")
//   "ApiActivityLogEntities" — columns: "apiActivityLogId", "entitiesId" (joins "API Activity Log" and "Entities")
import { createTableClient, createSqlClient, createAuthClient } from 'zitejs/runtime';

/** An attachment as returned when reading a record. */
export type ZiteAttachment = {
  /** Original filename as uploaded. */
  filename: string;
  /** Display name — may differ from `filename`. */
  originalName: string;
  /** File size in bytes. */
  size: number;
  mimeType: string;
  /** Publicly accessible URL. */
  url: string;
  /** ISO timestamp of the upload. */
  uploadedAt: string;
  metadata?: Record<string, unknown>;
};

/** What you may write to an attachments field: a URL, a URL with a name, or an attachment you read earlier. */
export type ZiteAttachmentInput =
  | string
  | { url: string; filename?: string }
  | ZiteAttachment;

/** A record in the "Invitations" table, as it is read back. */
export type InvitationsRecordType = {
  id: string;
  /** Primary field. "Code" */
  code?: string;
  entityName?: string;
  entityType?: "Dealer" | "Supplier" | "Anchor Buyer" | "Anchor" | string;
  contactEmail?: string;
  contactPhone?: string;
  status?: "Pending Sign-up" | "Signed Up" | "Onboarding" | "Expired" | string;
  sentVia?: ("Email" | "SMS" | string)[];
  /** "Sent At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  sentAt?: string;
  /** "Expires At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  expiresAt?: string;
  createdBy?: string | string[];
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  productType?: "Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string;
  /** Links to programs ("Programs"). "Program" */
  program?: string | string[];
  /** Links to entities ("Entities"). "Recommender Entity" */
  recommenderEntity?: string | string[];
  /** "Proposed Limit". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  proposedLimit?: number;
  notes?: string;
  /** Links to entities ("Entities"). "Entities" */
  entities?: string | string[];
  /** Links to onboardings ("Onboardings"). "Onboardings" */
  onboardings?: string | string[];
};

/** What you may write when creating or updating a record in the "Invitations" table. */
export type InvitationsRecordInput = {
  code: string | null;
  entityName: string | null;
  entityType: "Dealer" | "Supplier" | "Anchor Buyer" | "Anchor" | string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  status: "Pending Sign-up" | "Signed Up" | "Onboarding" | "Expired" | string | null;
  sentVia: "Email" | "SMS" | string | ("Email" | "SMS" | string)[] | null;
  sentAt: string | Date | null;
  expiresAt: string | Date | null;
  createdBy: string | string[] | null;
  productType: "Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string | null;
  program: string | string[] | null;
  recommenderEntity: string | string[] | null;
  proposedLimit: string | number | null;
  notes: string | null;
  entities: string | string[] | null;
  onboardings: string | string[] | null;
};

/** A record in the "Notifications" table, as it is read back. */
export type NotificationsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  message?: string;
  type?: "Entity Approved" | "Entity Rejected" | "Limit Offer" | "Financing Approved" | "Disbursement" | "Repayment Confirmed" | "Loan Overdue" | "Compliance Alert" | string;
  read?: boolean;
  linkPath?: string;
  recipient?: string | string[];
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
};

/** What you may write when creating or updating a record in the "Notifications" table. */
export type NotificationsRecordInput = {
  title: string | null;
  message: string | null;
  type: "Entity Approved" | "Entity Rejected" | "Limit Offer" | "Financing Approved" | "Disbursement" | "Repayment Confirmed" | "Loan Overdue" | "Compliance Alert" | string | null;
  read: string | boolean | null;
  linkPath: string | null;
  recipient: string | string[] | null;
};

/** A record in the "System Settings" table, as it is read back. */
export type SystemSettingsRecordType = {
  id: string;
  /** Primary field. "Key" */
  key?: string;
  value?: string;
  description?: string;
  /** Read-only. "Updated At". Auto-set when record was last modified (ISO 8601) */
  updatedAt?: string;
  updatedBy?: string;
};

/** What you may write when creating or updating a record in the "System Settings" table. */
export type SystemSettingsRecordInput = {
  key: string | null;
  value: string | null;
  description: string | null;
};

/** A record in the "Backoffice Users" table, as it is read back. */
export type BackofficeUsersRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  role?: "Super Admin" | "Maker" | "Checker" | "FI Admin" | "FI Checker" | "Master Anchor Admin" | string;
  user?: string | string[];
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  /** Links to apiPartners ("API Partners"). "API Partner" */
  apiPartner?: string | string[];
};

/** What you may write when creating or updating a record in the "Backoffice Users" table. */
export type BackofficeUsersRecordInput = {
  name: string | null;
  role: "Super Admin" | "Maker" | "Checker" | "FI Admin" | "FI Checker" | "Master Anchor Admin" | string | null;
  user: string | string[] | null;
  apiPartner: string | string[] | null;
};

/** A record in the "Entities" table, as it is read back. */
export type EntitiesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  entityType?: "Dealer" | "Supplier" | "Anchor Buyer" | "Anchor" | "Master Anchor" | "FI" | string;
  kycStatus?: "Pending" | "In Review" | "Approved" | "Rejected" | string;
  contactEmail?: string;
  contactPhone?: string;
  registrationNumber?: string;
  /** "Approved Limit". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  approvedLimit?: number;
  /** Links to invitations ("Invitations"). "Invitation" */
  invitation?: string | string[];
  owner?: string | string[];
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  kraPin?: string;
  businessSector?: string;
  physicalAddress?: string;
  onboardingStatus?: "Not Started" | "In Progress" | "Awaiting Review" | "Active" | "Suspended" | string;
  /** Links to invitations ("Invitations"). "Invitations" */
  invitations?: string | string[];
  /** Links to programs ("Programs"). "Programs" */
  programs?: string | string[];
  /** Links to loans ("Loans"). "Loans" */
  loans?: string | string[];
  /** Links to onboardings ("Onboardings"). "Onboardings" */
  onboardings?: string | string[];
  /** Links to entityOwners ("Entity Owners"). "Entity Owners" */
  entityOwners?: string | string[];
  /** Links to entityOperators ("Entity Operators"). "Entity Operators" */
  entityOperators?: string | string[];
  /** Links to limitProposals ("Limit Proposals"). "Limit Proposals" */
  limitProposals?: string | string[];
  /** Links to invoices ("Invoices"). "Invoices" */
  invoices?: string | string[];
  /** Links to invoices ("Invoices"). "Invoices (1)" */
  invoices1?: string | string[];
  /** Links to financingRequests ("Financing Requests"). "Financing Requests" */
  financingRequests?: string | string[];
  /** Links to financingRequests ("Financing Requests"). "Financing Requests (1)" */
  financingRequests1?: string | string[];
  /** Links to offerLetters ("Offer Letters"). "Offer Letters" */
  offerLetters?: string | string[];
  /** Links to journalEntries ("Journal Entries"). "Journal Entries" */
  journalEntries?: string | string[];
  /** Links to creditScores ("Credit Scores"). "Credit Scores" */
  creditScores?: string | string[];
  /** Links to riskAlerts ("Risk Alerts"). "Risk Alerts" */
  riskAlerts?: string | string[];
  /** Links to bankAccounts ("Bank Accounts"). "Bank Accounts" */
  bankAccounts?: string | string[];
  /** Links to assetSchedules ("Asset Schedules"). "Asset Schedules" */
  assetSchedules?: string | string[];
  /** Links to warehouseReceipts ("Warehouse Receipts"). "Warehouse Receipts" */
  warehouseReceipts?: string | string[];
  /** Links to apiActivityLog ("API Activity Log"). "API Activity Log" */
  apiActivityLog?: string | string[];
  /** Links to apiPartners ("API Partners"). "Created By Partner" */
  createdByPartner?: string | string[];
  allowSelfInvoicing?: boolean;
};

/** What you may write when creating or updating a record in the "Entities" table. */
export type EntitiesRecordInput = {
  name: string | null;
  entityType: "Dealer" | "Supplier" | "Anchor Buyer" | "Anchor" | "Master Anchor" | "FI" | string | null;
  kycStatus: "Pending" | "In Review" | "Approved" | "Rejected" | string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  registrationNumber: string | null;
  approvedLimit: string | number | null;
  invitation: string | string[] | null;
  owner: string | string[] | null;
  kraPin: string | null;
  businessSector: string | null;
  physicalAddress: string | null;
  onboardingStatus: "Not Started" | "In Progress" | "Awaiting Review" | "Active" | "Suspended" | string | null;
  invitations: string | string[] | null;
  programs: string | string[] | null;
  loans: string | string[] | null;
  onboardings: string | string[] | null;
  entityOwners: string | string[] | null;
  entityOperators: string | string[] | null;
  limitProposals: string | string[] | null;
  invoices: string | string[] | null;
  invoices1: string | string[] | null;
  financingRequests: string | string[] | null;
  financingRequests1: string | string[] | null;
  offerLetters: string | string[] | null;
  journalEntries: string | string[] | null;
  creditScores: string | string[] | null;
  riskAlerts: string | string[] | null;
  bankAccounts: string | string[] | null;
  assetSchedules: string | string[] | null;
  warehouseReceipts: string | string[] | null;
  apiActivityLog: string | string[] | null;
  createdByPartner: string | string[] | null;
  allowSelfInvoicing: string | boolean | null;
};

/** A record in the "Programs" table, as it is read back. */
export type ProgramsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  productType?: "Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string;
  /** Links to entities ("Entities"). "Anchor Entity" */
  anchorEntity?: string | string[];
  status?: "Active" | "Suspended" | "Closed" | string;
  description?: string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  /** "Program Size". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  programSize?: number;
  /** "Credit Period Days". 0 decimal places, format: local (e.g. 1,000,000.50) */
  creditPeriodDays?: number;
  /** "Finance Percentage". 1 decimal places */
  financePercentage?: number;
  /** "Min Participant Limit". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  minParticipantLimit?: number;
  /** "Max Participant Limit". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  maxParticipantLimit?: number;
  /** "Approval Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  approvalDate?: string;
  /** "Renewal Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  renewalDate?: string;
  programOwnerType?: "Master Anchor" | "Anchor Buyer" | "FI" | string;
  /** Links to invitations ("Invitations"). "Invitations" */
  invitations?: string | string[];
  /** Links to loans ("Loans"). "Loans" */
  loans?: string | string[];
  /** Links to onboardings ("Onboardings"). "Onboardings" */
  onboardings?: string | string[];
  /** Links to limitProposals ("Limit Proposals"). "Limit Proposals" */
  limitProposals?: string | string[];
  /** Links to invoices ("Invoices"). "Invoices" */
  invoices?: string | string[];
  /** Links to financingRequests ("Financing Requests"). "Financing Requests" */
  financingRequests?: string | string[];
  /** Links to offerLetters ("Offer Letters"). "Offer Letters" */
  offerLetters?: string | string[];
  /** Links to fiProgramPricing ("FI Program Pricing"). "FI Program Pricing" */
  fiProgramPricing?: string | string[];
  /** Links to journalEntries ("Journal Entries"). "Journal Entries" */
  journalEntries?: string | string[];
  /** Links to riskAlerts ("Risk Alerts"). "Risk Alerts" */
  riskAlerts?: string | string[];
  /** Links to assetSchedules ("Asset Schedules"). "Asset Schedules" */
  assetSchedules?: string | string[];
  /** Links to warehouseReceipts ("Warehouse Receipts"). "Warehouse Receipts" */
  warehouseReceipts?: string | string[];
  /** Links to apiPartners ("API Partners"). "Created By Partner" */
  createdByPartner?: string | string[];
};

/** What you may write when creating or updating a record in the "Programs" table. */
export type ProgramsRecordInput = {
  name: string | null;
  productType: "Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string | null;
  anchorEntity: string | string[] | null;
  status: "Active" | "Suspended" | "Closed" | string | null;
  description: string | null;
  programSize: string | number | null;
  creditPeriodDays: string | number | null;
  financePercentage: string | number | null;
  minParticipantLimit: string | number | null;
  maxParticipantLimit: string | number | null;
  approvalDate: string | Date | null;
  renewalDate: string | Date | null;
  programOwnerType: "Master Anchor" | "Anchor Buyer" | "FI" | string | null;
  invitations: string | string[] | null;
  loans: string | string[] | null;
  onboardings: string | string[] | null;
  limitProposals: string | string[] | null;
  invoices: string | string[] | null;
  financingRequests: string | string[] | null;
  offerLetters: string | string[] | null;
  fiProgramPricing: string | string[] | null;
  journalEntries: string | string[] | null;
  riskAlerts: string | string[] | null;
  assetSchedules: string | string[] | null;
  warehouseReceipts: string | string[] | null;
  createdByPartner: string | string[] | null;
};

/** A record in the "Loans" table, as it is read back. */
export type LoansRecordType = {
  id: string;
  /** Primary field. "Loan Reference" */
  loanReference?: string;
  /** Links to entities ("Entities"). "Entity" */
  entity?: string | string[];
  /** Links to programs ("Programs"). "Program" */
  program?: string | string[];
  productType?: "Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string;
  /** "Principal". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  principal?: number;
  /** "Outstanding Balance". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  outstandingBalance?: number;
  /** "Interest Rate". 2 decimal places */
  interestRate?: number;
  /** "Penalty Amount". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  penaltyAmount?: number;
  status?: "Active" | "Overdue" | "Settled" | "Written Off" | string;
  /** "Disbursed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  disbursedAt?: string;
  /** "Maturity Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  maturityDate?: string;
  /** "Days Overdue". 1 decimal places, format: local (e.g. 1,000,000.50) */
  daysOverdue?: number;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  borrowerEntityType?: "Dealer" | "Anchor Buyer" | "Supplier" | string;
  /** Links to transactions ("Transactions"). "Transactions" */
  transactions?: string | string[];
  /** Links to financingRequests ("Financing Requests"). "Financing Requests" */
  financingRequests?: string | string[];
  /** Links to journalEntries ("Journal Entries"). "Journal Entries" */
  journalEntries?: string | string[];
  /** Links to assetSchedules ("Asset Schedules"). "Asset Schedules" */
  assetSchedules?: string | string[];
  /** Links to warehouseReceipts ("Warehouse Receipts"). "Warehouse Receipts" */
  warehouseReceipts?: string | string[];
};

/** What you may write when creating or updating a record in the "Loans" table. */
export type LoansRecordInput = {
  loanReference: string | null;
  entity: string | string[] | null;
  program: string | string[] | null;
  productType: "Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string | null;
  principal: string | number | null;
  outstandingBalance: string | number | null;
  interestRate: string | number | null;
  penaltyAmount: string | number | null;
  status: "Active" | "Overdue" | "Settled" | "Written Off" | string | null;
  disbursedAt: string | Date | null;
  maturityDate: string | Date | null;
  daysOverdue: string | number | null;
  borrowerEntityType: "Dealer" | "Anchor Buyer" | "Supplier" | string | null;
  transactions: string | string[] | null;
  financingRequests: string | string[] | null;
  journalEntries: string | string[] | null;
  assetSchedules: string | string[] | null;
  warehouseReceipts: string | string[] | null;
};

/** A record in the "Transactions" table, as it is read back. */
export type TransactionsRecordType = {
  id: string;
  /** Primary field. "Reference" */
  reference?: string;
  /** Links to loans ("Loans"). "Loan" */
  loan?: string | string[];
  type?: "Disbursement" | "Repayment" | "Penalty" | "Interest" | "Fee" | string;
  /** "Amount". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  amount?: number;
  paymentMethod?: "M-Pesa" | "Bank Transfer" | "System" | string;
  mPesaReceipt?: string;
  phoneNumber?: string;
  status?: "Pending" | "Completed" | "Failed" | "Reversed" | string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
};

/** What you may write when creating or updating a record in the "Transactions" table. */
export type TransactionsRecordInput = {
  reference: string | null;
  loan: string | string[] | null;
  type: "Disbursement" | "Repayment" | "Penalty" | "Interest" | "Fee" | string | null;
  amount: string | number | null;
  paymentMethod: "M-Pesa" | "Bank Transfer" | "System" | string | null;
  mPesaReceipt: string | null;
  phoneNumber: string | null;
  status: "Pending" | "Completed" | "Failed" | "Reversed" | string | null;
};

/** A record in the "Onboardings" table, as it is read back. */
export type OnboardingsRecordType = {
  id: string;
  /** Primary field. Read-only. "Onboarding Number" */
  onboardingNumber?: number;
  /** Links to entities ("Entities"). "Entity" */
  entity?: string | string[];
  /** Links to programs ("Programs"). "Program" */
  program?: string | string[];
  productType?: "Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string;
  entityType?: "Dealer" | "Supplier" | "Anchor Buyer" | "Anchor" | string;
  currentStage?: "Business Details" | "Document Upload" | "Owner Details" | "Owner KYC Documents" | "Location Photo" | "Bank Statement" | "Bank Details" | "Operators" | "Limit Proposal" | "Submitted for Review" | "Maker Review" | "Checker Review" | "FI Document Review" | "Sent to FI" | "Offer Generated" | "Awaiting Offer Response" | "Completed" | string;
  overallStatus?: "Not Started" | "In Progress" | "Awaiting Review" | "Approved" | "Rejected" | "Pending FI Review" | "FI Approved" | "Sent to FI" | "Offer Received" | "Offer Accepted" | "Completed" | string;
  owner?: string | string[];
  /** Links to invitations ("Invitations"). "Invitation" */
  invitation?: string | string[];
  businessDetailsJson?: string;
  bankDetailsJson?: string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  /** Read-only. "Updated At". Auto-set when record was last modified (ISO 8601) */
  updatedAt?: string;
  makerReviewedBy?: string;
  /** "Maker Reviewed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  makerReviewedAt?: string;
  makerNotes?: string;
  checkerReviewedBy?: string;
  /** "Checker Reviewed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  checkerReviewedAt?: string;
  checkerNotes?: string;
  fiReviewedBy?: string;
  /** "FI Reviewed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  fiReviewedAt?: string;
  fiReviewNotes?: string;
  /** Links to onboardingDocuments ("Onboarding Documents"). "Onboarding Documents" */
  onboardingDocuments?: string | string[];
  /** Links to limitProposals ("Limit Proposals"). "Limit Proposals" */
  limitProposals?: string | string[];
  /** Links to offerLetters ("Offer Letters"). "Offer Letters" */
  offerLetters?: string | string[];
};

/** What you may write when creating or updating a record in the "Onboardings" table. */
export type OnboardingsRecordInput = {
  entity: string | string[] | null;
  program: string | string[] | null;
  productType: "Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string | null;
  entityType: "Dealer" | "Supplier" | "Anchor Buyer" | "Anchor" | string | null;
  currentStage: "Business Details" | "Document Upload" | "Owner Details" | "Owner KYC Documents" | "Location Photo" | "Bank Statement" | "Bank Details" | "Operators" | "Limit Proposal" | "Submitted for Review" | "Maker Review" | "Checker Review" | "FI Document Review" | "Sent to FI" | "Offer Generated" | "Awaiting Offer Response" | "Completed" | string | null;
  overallStatus: "Not Started" | "In Progress" | "Awaiting Review" | "Approved" | "Rejected" | "Pending FI Review" | "FI Approved" | "Sent to FI" | "Offer Received" | "Offer Accepted" | "Completed" | string | null;
  owner: string | string[] | null;
  invitation: string | string[] | null;
  businessDetailsJson: string | null;
  bankDetailsJson: string | null;
  makerReviewedBy: string | null;
  makerReviewedAt: string | Date | null;
  makerNotes: string | null;
  checkerReviewedBy: string | null;
  checkerReviewedAt: string | Date | null;
  checkerNotes: string | null;
  fiReviewedBy: string | null;
  fiReviewedAt: string | Date | null;
  fiReviewNotes: string | null;
  onboardingDocuments: string | string[] | null;
  limitProposals: string | string[] | null;
  offerLetters: string | string[] | null;
};

/** A record in the "Onboarding Documents" table, as it is read back. */
export type OnboardingDocumentsRecordType = {
  id: string;
  /** Primary field. "Document Name" */
  documentName?: string;
  /** Links to onboardings ("Onboardings"). "Onboarding" */
  onboarding?: string | string[];
  documentType?: "Business Registration" | "KRA PIN Certificate" | "CR12" | "National ID" | "Passport" | "Owner Photo" | "Location Photo" | "Bank Statement" | "Business Permit" | string;
  file?: ZiteAttachment[];
  verificationStatus?: "Pending Verification" | "Verified" | "Rejected" | string;
  notes?: string;
  /** Read-only. "Uploaded At". Auto-set when record was created (ISO 8601) */
  uploadedAt?: string;
};

/** What you may write when creating or updating a record in the "Onboarding Documents" table. */
export type OnboardingDocumentsRecordInput = {
  documentName: string | null;
  onboarding: string | string[] | null;
  documentType: "Business Registration" | "KRA PIN Certificate" | "CR12" | "National ID" | "Passport" | "Owner Photo" | "Location Photo" | "Bank Statement" | "Business Permit" | string | null;
  file: ZiteAttachmentInput[] | ZiteAttachmentInput | null;
  verificationStatus: "Pending Verification" | "Verified" | "Rejected" | string | null;
  notes: string | null;
};

/** A record in the "Entity Owners" table, as it is read back. */
export type EntityOwnersRecordType = {
  id: string;
  /** Primary field. "Full Name" */
  fullName?: string;
  /** Links to entities ("Entities"). "Entity" */
  entity?: string | string[];
  idNumber?: string;
  idType?: "National ID" | "Passport" | string;
  /** "Date of Birth". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  dateOfBirth?: string;
  phone?: string;
  email?: string;
  /** "Ownership Percentage". 0 decimal places */
  ownershipPercentage?: number;
  isPrimaryContact?: boolean;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
};

/** What you may write when creating or updating a record in the "Entity Owners" table. */
export type EntityOwnersRecordInput = {
  fullName: string | null;
  entity: string | string[] | null;
  idNumber: string | null;
  idType: "National ID" | "Passport" | string | null;
  dateOfBirth: string | Date | null;
  phone: string | null;
  email: string | null;
  ownershipPercentage: string | number | null;
  isPrimaryContact: string | boolean | null;
};

/** A record in the "Entity Operators" table, as it is read back. */
export type EntityOperatorsRecordType = {
  id: string;
  /** Primary field. "Full Name" */
  fullName?: string;
  /** Links to entities ("Entities"). "Entity" */
  entity?: string | string[];
  email?: string;
  phone?: string;
  role?: string;
  isAuthorizedSignatory?: boolean;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
};

/** What you may write when creating or updating a record in the "Entity Operators" table. */
export type EntityOperatorsRecordInput = {
  fullName: string | null;
  entity: string | string[] | null;
  email: string | null;
  phone: string | null;
  role: string | null;
  isAuthorizedSignatory: string | boolean | null;
};

/** A record in the "Limit Proposals" table, as it is read back. */
export type LimitProposalsRecordType = {
  id: string;
  /** Primary field. Read-only. "Proposal Number" */
  proposalNumber?: number;
  /** Links to entities ("Entities"). "Entity" */
  entity?: string | string[];
  /** Links to programs ("Programs"). "Program" */
  program?: string | string[];
  /** Links to onboardings ("Onboardings"). "Onboarding" */
  onboarding?: string | string[];
  /** "Proposed Amount". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  proposedAmount?: number;
  /** "Approved Amount". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  approvedAmount?: number;
  currency?: string;
  /** "Preferred Tenor Days". 1 decimal places, format: local (e.g. 1,000,000.50) */
  preferredTenorDays?: number;
  status?: "Pending" | "Assessed" | "Approved" | "Rejected" | "Under Review" | string;
  justification?: string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  assessedBy?: string;
  /** "Assessed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  assessedAt?: string;
  approvedBy?: string;
  /** "Approved At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  approvedAt?: string;
  rejectionReason?: string;
};

/** What you may write when creating or updating a record in the "Limit Proposals" table. */
export type LimitProposalsRecordInput = {
  entity: string | string[] | null;
  program: string | string[] | null;
  onboarding: string | string[] | null;
  proposedAmount: string | number | null;
  approvedAmount: string | number | null;
  currency: string | null;
  preferredTenorDays: string | number | null;
  status: "Pending" | "Assessed" | "Approved" | "Rejected" | "Under Review" | string | null;
  justification: string | null;
  assessedBy: string | null;
  assessedAt: string | Date | null;
  approvedBy: string | null;
  approvedAt: string | Date | null;
  rejectionReason: string | null;
};

/** A record in the "Invoices" table, as it is read back. */
export type InvoicesRecordType = {
  id: string;
  /** Primary field. "Invoice Number" */
  invoiceNumber?: string;
  /** Links to entities ("Entities"). "Issuer Entity" */
  issuerEntity?: string | string[];
  /** Links to entities ("Entities"). "Recipient Entity" */
  recipientEntity?: string | string[];
  /** Links to programs ("Programs"). "Program" */
  program?: string | string[];
  productType?: "Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string;
  /** "Amount". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  amount?: number;
  /** "Issue Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  issueDate?: string;
  /** "Due Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  dueDate?: string;
  status?: "Uploaded" | "Pending Verification" | "Verified" | "Finance Eligible" | "Finance Requested" | "Financing Approved" | "Fully Financed" | "Early Paid" | "Partially Paid" | "Paid" | "Financed" | "Approved" | string;
  description?: string;
  document?: ZiteAttachment[];
  purchaseOrderNumber?: string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  /** Links to financingRequests ("Financing Requests"). "Financing Requests" */
  financingRequests?: string | string[];
};

/** What you may write when creating or updating a record in the "Invoices" table. */
export type InvoicesRecordInput = {
  invoiceNumber: string | null;
  issuerEntity: string | string[] | null;
  recipientEntity: string | string[] | null;
  program: string | string[] | null;
  productType: "Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string | null;
  amount: string | number | null;
  issueDate: string | Date | null;
  dueDate: string | Date | null;
  status: "Uploaded" | "Pending Verification" | "Verified" | "Finance Eligible" | "Finance Requested" | "Financing Approved" | "Fully Financed" | "Early Paid" | "Partially Paid" | "Paid" | "Financed" | "Approved" | string | null;
  description: string | null;
  document: ZiteAttachmentInput[] | ZiteAttachmentInput | null;
  purchaseOrderNumber: string | null;
  financingRequests: string | string[] | null;
};

/** A record in the "Financing Requests" table, as it is read back. */
export type FinancingRequestsRecordType = {
  id: string;
  /** Primary field. Read-only. "Request Number" */
  requestNumber?: number;
  /** Links to entities ("Entities"). "Requesting Entity" */
  requestingEntity?: string | string[];
  /** Links to entities ("Entities"). "Borrower Entity" */
  borrowerEntity?: string | string[];
  /** Links to programs ("Programs"). "Program" */
  program?: string | string[];
  /** Links to invoices ("Invoices"). "Invoices" */
  invoices?: string | string[];
  productType?: "Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string;
  /** "Requested Amount". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  requestedAmount?: number;
  /** "Financeable Amount". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  financeableAmount?: number;
  /** "Interest Rate". 2 decimal places, format: local (e.g. 1,000,000.50) */
  interestRate?: number;
  /** "Tenor Days". 1 decimal places, format: local (e.g. 1,000,000.50) */
  tenorDays?: number;
  status?: "Requested" | "Pending Approval" | "Approved" | "Rejected" | "Disbursed" | "Pending" | "Under Review" | string;
  /** Links to loans ("Loans"). "Loan" */
  loan?: string | string[];
  comments?: string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  assessedBy?: string;
  /** "Assessed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  assessedAt?: string;
  approvedBy?: string;
  /** "Approved At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  approvedAt?: string;
  rejectionReason?: string;
  currency?: string;
  /** Links to journalEntries ("Journal Entries"). "Journal Entries" */
  journalEntries?: string | string[];
  /** Links to fiProgramPricing ("FI Program Pricing"). "Selected FI Pricing" */
  selectedFiPricing?: string | string[];
};

/** What you may write when creating or updating a record in the "Financing Requests" table. */
export type FinancingRequestsRecordInput = {
  requestingEntity: string | string[] | null;
  borrowerEntity: string | string[] | null;
  program: string | string[] | null;
  invoices: string | string[] | null;
  productType: "Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string | null;
  requestedAmount: string | number | null;
  financeableAmount: string | number | null;
  interestRate: string | number | null;
  tenorDays: string | number | null;
  status: "Requested" | "Pending Approval" | "Approved" | "Rejected" | "Disbursed" | "Pending" | "Under Review" | string | null;
  loan: string | string[] | null;
  comments: string | null;
  assessedBy: string | null;
  assessedAt: string | Date | null;
  approvedBy: string | null;
  approvedAt: string | Date | null;
  rejectionReason: string | null;
  currency: string | null;
  journalEntries: string | string[] | null;
  selectedFiPricing: string | string[] | null;
};

/** A record in the "Offer Letters" table, as it is read back. */
export type OfferLettersRecordType = {
  id: string;
  /** Primary field. Read-only. "Offer Number" */
  offerNumber?: number;
  /** Links to entities ("Entities"). "Entity" */
  entity?: string | string[];
  /** Links to onboardings ("Onboardings"). "Onboarding" */
  onboarding?: string | string[];
  /** Links to programs ("Programs"). "Program" */
  program?: string | string[];
  /** "Approved Limit". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  approvedLimit?: number;
  /** "Interest Rate". 2 decimal places, format: local (e.g. 1,000,000.50) */
  interestRate?: number;
  /** "Tenor Days". 1 decimal places, format: local (e.g. 1,000,000.50) */
  tenorDays?: number;
  status?: "Generated" | "Accepted" | "Rejected" | "Expired" | string;
  /** "Expiry Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  expiryDate?: string;
  document?: ZiteAttachment[];
  notes?: string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
};

/** What you may write when creating or updating a record in the "Offer Letters" table. */
export type OfferLettersRecordInput = {
  entity: string | string[] | null;
  onboarding: string | string[] | null;
  program: string | string[] | null;
  approvedLimit: string | number | null;
  interestRate: string | number | null;
  tenorDays: string | number | null;
  status: "Generated" | "Accepted" | "Rejected" | "Expired" | string | null;
  expiryDate: string | Date | null;
  document: ZiteAttachmentInput[] | ZiteAttachmentInput | null;
  notes: string | null;
};

/** A record in the "Financial Institutions" table, as it is read back. */
export type FinancialInstitutionsRecordType = {
  id: string;
  /** Primary field. "Legal Name" */
  legalName?: string;
  tradingName?: string;
  contactEmail?: string;
  contactPhone?: string;
  bankCode?: string;
  swiftCode?: string;
  status?: "Active" | "Pending" | "Inactive" | string;
  country?: string;
  currency?: string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  /** Links to fiProgramPricing ("FI Program Pricing"). "FI Program Pricing" */
  fiProgramPricing?: string | string[];
};

/** What you may write when creating or updating a record in the "Financial Institutions" table. */
export type FinancialInstitutionsRecordInput = {
  legalName: string | null;
  tradingName: string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  bankCode: string | null;
  swiftCode: string | null;
  status: "Active" | "Pending" | "Inactive" | string | null;
  country: string | null;
  currency: string | null;
  fiProgramPricing: string | string[] | null;
};

/** A record in the "FI Program Pricing" table, as it is read back. */
export type FiProgramPricingRecordType = {
  id: string;
  /** Primary field. "Pricing Name" */
  pricingName?: string;
  /** Links to financialInstitutions ("Financial Institutions"). "Financial Institution" */
  financialInstitution?: string | string[];
  /** Links to programs ("Programs"). "Program" */
  program?: string | string[];
  productType?: "Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string;
  /** "Min Limit". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  minLimit?: number;
  /** "Max Limit". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  maxLimit?: number;
  /** "Transaction Fee Rate". 2 decimal places */
  transactionFeeRate?: number;
  /** "Processing Fee Fixed". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  processingFeeFixed?: number;
  /** "Processing Fee Rate". 2 decimal places */
  processingFeeRate?: number;
  /** "Penalty Fee Rate". 2 decimal places */
  penaltyFeeRate?: number;
  /** "Past Due Daily Rate". 4 decimal places */
  pastDueDailyRate?: number;
  repaymentBankAccount?: string;
  tiersJson?: string;
  status?: "Active" | "Inactive" | string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  autoDisburse?: boolean;
  /** Links to financingRequests ("Financing Requests"). "Financing Requests" */
  financingRequests?: string | string[];
  /** "Interest Rate". 2 decimal places */
  interestRate?: number;
  /** "Tenor Days". 0 decimal places, format: local (e.g. 1,000,000.50) */
  tenorDays?: number;
  /** "Trove Fee Rate". 2 decimal places */
  troveFeeRate?: number;
  /** "Trove Fee Fixed". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  troveFeeFixed?: number;
  /** "FI Charge Rate". 2 decimal places */
  fiChargeRate?: number;
  /** "FI Charge Fixed". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  fiChargeFixed?: number;
};

/** What you may write when creating or updating a record in the "FI Program Pricing" table. */
export type FiProgramPricingRecordInput = {
  pricingName: string | null;
  financialInstitution: string | string[] | null;
  program: string | string[] | null;
  productType: "Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string | null;
  minLimit: string | number | null;
  maxLimit: string | number | null;
  transactionFeeRate: string | number | null;
  processingFeeFixed: string | number | null;
  processingFeeRate: string | number | null;
  penaltyFeeRate: string | number | null;
  pastDueDailyRate: string | number | null;
  repaymentBankAccount: string | null;
  tiersJson: string | null;
  status: "Active" | "Inactive" | string | null;
  autoDisburse: string | boolean | null;
  financingRequests: string | string[] | null;
  interestRate: string | number | null;
  tenorDays: string | number | null;
  troveFeeRate: string | number | null;
  troveFeeFixed: string | number | null;
  fiChargeRate: string | number | null;
  fiChargeFixed: string | number | null;
};

/** A record in the "GL Accounts" table, as it is read back. */
export type GlAccountsRecordType = {
  id: string;
  /** Primary field. "Account Number" */
  accountNumber?: string;
  accountName?: string;
  accountType?: "Asset" | "Liability" | "Equity" | "Revenue" | "Expense" | string;
  subType?: string;
  description?: string;
  isActive?: boolean;
  /** "Current Balance". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  currentBalance?: number;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  /** Links to journalLines ("Journal Lines"). "Journal Lines" */
  journalLines?: string | string[];
};

/** What you may write when creating or updating a record in the "GL Accounts" table. */
export type GlAccountsRecordInput = {
  accountNumber: string | null;
  accountName: string | null;
  accountType: "Asset" | "Liability" | "Equity" | "Revenue" | "Expense" | string | null;
  subType: string | null;
  description: string | null;
  isActive: string | boolean | null;
  currentBalance: string | number | null;
  journalLines: string | string[] | null;
};

/** A record in the "Journal Entries" table, as it is read back. */
export type JournalEntriesRecordType = {
  id: string;
  /** Primary field. Read-only. "Entry Number" */
  entryNumber?: number;
  /** "Entry Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  entryDate?: string;
  reference?: string;
  description?: string;
  status?: "Draft" | "Posted" | "Reversed" | string;
  /** "Total Amount". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  totalAmount?: number;
  postedBy?: string;
  /** Links to entities ("Entities"). "Entity" */
  entity?: string | string[];
  /** Links to programs ("Programs"). "Program" */
  program?: string | string[];
  /** Links to financingRequests ("Financing Requests"). "Financing Request" */
  financingRequest?: string | string[];
  /** Links to loans ("Loans"). "Loan" */
  loan?: string | string[];
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  /** Links to journalLines ("Journal Lines"). "Journal Lines" */
  journalLines?: string | string[];
};

/** What you may write when creating or updating a record in the "Journal Entries" table. */
export type JournalEntriesRecordInput = {
  entryDate: string | Date | null;
  reference: string | null;
  description: string | null;
  status: "Draft" | "Posted" | "Reversed" | string | null;
  totalAmount: string | number | null;
  postedBy: string | null;
  entity: string | string[] | null;
  program: string | string[] | null;
  financingRequest: string | string[] | null;
  loan: string | string[] | null;
  journalLines: string | string[] | null;
};

/** A record in the "Journal Lines" table, as it is read back. */
export type JournalLinesRecordType = {
  id: string;
  /** Primary field. Read-only. "Line Number" */
  lineNumber?: number;
  /** Links to journalEntries ("Journal Entries"). "Journal Entry" */
  journalEntry?: string | string[];
  /** Links to glAccounts ("GL Accounts"). "GL Account" */
  glAccount?: string | string[];
  /** "Debit Amount". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  debitAmount?: number;
  /** "Credit Amount". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  creditAmount?: number;
  narration?: string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
};

/** What you may write when creating or updating a record in the "Journal Lines" table. */
export type JournalLinesRecordInput = {
  journalEntry: string | string[] | null;
  glAccount: string | string[] | null;
  debitAmount: string | number | null;
  creditAmount: string | number | null;
  narration: string | null;
};

/** A record in the "Credit Scores" table, as it is read back. */
export type CreditScoresRecordType = {
  id: string;
  /** Primary field. "Entity Name" */
  entityName?: string;
  /** Links to entities ("Entities"). "Entity" */
  entity?: string | string[];
  /** "Score". 0 decimal places, format: local (e.g. 1,000,000.50) */
  score?: number;
  rating?: "A+" | "A" | "B" | "C" | "D" | string;
  /** "Payment Timeliness Score". 1 decimal places, format: local (e.g. 1,000,000.50) */
  paymentTimelinessScore?: number;
  /** "Trade Volume Score". 1 decimal places, format: local (e.g. 1,000,000.50) */
  tradeVolumeScore?: number;
  /** "Default Rate Score". 1 decimal places, format: local (e.g. 1,000,000.50) */
  defaultRateScore?: number;
  /** "Entity Age Score". 1 decimal places, format: local (e.g. 1,000,000.50) */
  entityAgeScore?: number;
  /** "Product Diversity Score". 1 decimal places, format: local (e.g. 1,000,000.50) */
  productDiversityScore?: number;
  /** "On Time Percent". 1 decimal places */
  onTimePercent?: number;
  /** "Total Trade Volume". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  totalTradeVolume?: number;
  /** "Default Rate". 1 decimal places */
  defaultRate?: number;
  aiSummary?: string;
  /** "Computed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  computedAt?: string;
};

/** What you may write when creating or updating a record in the "Credit Scores" table. */
export type CreditScoresRecordInput = {
  entityName: string | null;
  entity: string | string[] | null;
  score: string | number | null;
  rating: "A+" | "A" | "B" | "C" | "D" | string | null;
  paymentTimelinessScore: string | number | null;
  tradeVolumeScore: string | number | null;
  defaultRateScore: string | number | null;
  entityAgeScore: string | number | null;
  productDiversityScore: string | number | null;
  onTimePercent: string | number | null;
  totalTradeVolume: string | number | null;
  defaultRate: string | number | null;
  aiSummary: string | null;
  computedAt: string | Date | null;
};

/** A record in the "Risk Alerts" table, as it is read back. */
export type RiskAlertsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  /** Links to entities ("Entities"). "Entity" */
  entity?: string | string[];
  alertType?: "Invoice Volume Spike" | "Payment Pattern Shift" | "Credit Score Decline" | "Rapid Financing Requests" | "Potential Duplicate Invoice" | "Limit Breach Attempt" | string;
  severity?: "Critical" | "Warning" | "Info" | string;
  description?: string;
  status?: "Open" | "Investigating" | "Resolved" | "Dismissed" | string;
  resolvedBy?: string | string[];
  resolutionNotes?: string;
  /** "Detected At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  detectedAt?: string;
  /** Links to programs ("Programs"). "Program" */
  program?: string | string[];
};

/** What you may write when creating or updating a record in the "Risk Alerts" table. */
export type RiskAlertsRecordInput = {
  title: string | null;
  entity: string | string[] | null;
  alertType: "Invoice Volume Spike" | "Payment Pattern Shift" | "Credit Score Decline" | "Rapid Financing Requests" | "Potential Duplicate Invoice" | "Limit Breach Attempt" | string | null;
  severity: "Critical" | "Warning" | "Info" | string | null;
  description: string | null;
  status: "Open" | "Investigating" | "Resolved" | "Dismissed" | string | null;
  resolvedBy: string | string[] | null;
  resolutionNotes: string | null;
  detectedAt: string | Date | null;
  program: string | string[] | null;
};

/** A record in the "Bank Accounts" table, as it is read back. */
export type BankAccountsRecordType = {
  id: string;
  /** Primary field. "Account Name" */
  accountName?: string;
  /** Links to entities ("Entities"). "Entity" */
  entity?: string | string[];
  bankName?: string;
  branchName?: string;
  accountNumber?: string;
  bankCode?: string;
  branchCode?: string;
  swiftCode?: string;
  accountType?: "Current" | "Savings" | "Mobile Money" | string;
  mobileMoneyNumber?: string;
  currency?: "KES" | "USD" | "EUR" | string;
  isPrimary?: boolean;
  isVerified?: boolean;
  status?: "Active" | "Inactive" | "Pending Verification" | string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
};

/** What you may write when creating or updating a record in the "Bank Accounts" table. */
export type BankAccountsRecordInput = {
  accountName: string | null;
  entity: string | string[] | null;
  bankName: string | null;
  branchName: string | null;
  accountNumber: string | null;
  bankCode: string | null;
  branchCode: string | null;
  swiftCode: string | null;
  accountType: "Current" | "Savings" | "Mobile Money" | string | null;
  mobileMoneyNumber: string | null;
  currency: "KES" | "USD" | "EUR" | string | null;
  isPrimary: string | boolean | null;
  isVerified: string | boolean | null;
  status: "Active" | "Inactive" | "Pending Verification" | string | null;
};

/** A record in the "Asset Schedules" table, as it is read back. */
export type AssetSchedulesRecordType = {
  id: string;
  /** Primary field. "Asset Reference" */
  assetReference?: string;
  /** Links to entities ("Entities"). "Entity" */
  entity?: string | string[];
  /** Links to programs ("Programs"). "Program" */
  program?: string | string[];
  /** Links to loans ("Loans"). "Loan" */
  loan?: string | string[];
  assetDescription?: string;
  assetCategory?: "Vehicle" | "Equipment" | "Machinery" | "Property" | "Other" | string;
  serialNumber?: string;
  makeAndModel?: string;
  /** "Year Of Manufacture". 1 decimal places, format: local (e.g. 1,000,000.50) */
  yearOfManufacture?: number;
  /** "Asset Value". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  assetValue?: number;
  /** "Residual Value". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  residualValue?: number;
  /** "Lease Term Months". 1 decimal places, format: local (e.g. 1,000,000.50) */
  leaseTermMonths?: number;
  /** "Depreciation Rate". 0 decimal places */
  depreciationRate?: number;
  /** "Lease Start Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  leaseStartDate?: string;
  /** "Lease End Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  leaseEndDate?: string;
  status?: "Active" | "Returned" | "Written Off" | "Pending" | string;
  insurancePolicyNumber?: string;
  /** "Insurance Expiry". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  insuranceExpiry?: string;
  notes?: string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
};

/** What you may write when creating or updating a record in the "Asset Schedules" table. */
export type AssetSchedulesRecordInput = {
  assetReference: string | null;
  entity: string | string[] | null;
  program: string | string[] | null;
  loan: string | string[] | null;
  assetDescription: string | null;
  assetCategory: "Vehicle" | "Equipment" | "Machinery" | "Property" | "Other" | string | null;
  serialNumber: string | null;
  makeAndModel: string | null;
  yearOfManufacture: string | number | null;
  assetValue: string | number | null;
  residualValue: string | number | null;
  leaseTermMonths: string | number | null;
  depreciationRate: string | number | null;
  leaseStartDate: string | Date | null;
  leaseEndDate: string | Date | null;
  status: "Active" | "Returned" | "Written Off" | "Pending" | string | null;
  insurancePolicyNumber: string | null;
  insuranceExpiry: string | Date | null;
  notes: string | null;
};

/** A record in the "Warehouse Receipts" table, as it is read back. */
export type WarehouseReceiptsRecordType = {
  id: string;
  /** Primary field. "Receipt Number" */
  receiptNumber?: string;
  /** Links to entities ("Entities"). "Entity" */
  entity?: string | string[];
  /** Links to programs ("Programs"). "Program" */
  program?: string | string[];
  /** Links to loans ("Loans"). "Loan" */
  loan?: string | string[];
  warehouseName?: string;
  warehouseLocation?: string;
  commodityType?: string;
  grade?: string;
  /** "Quantity". 2 decimal places, format: local (e.g. 1,000,000.50) */
  quantity?: number;
  unitOfMeasure?: string;
  /** "Unit Price". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  unitPrice?: number;
  /** "Total Value". Value is a raw number; display as currency with symbol "KES", 2 decimal places, format: local (e.g. 1,000,000.50) */
  totalValue?: number;
  /** "Date Deposited". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  dateDeposited?: string;
  /** "Expiry Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  expiryDate?: string;
  status?: "Active" | "Released" | "Expired" | "Pledged" | string;
  collateralManager?: string;
  receiptDocument?: ZiteAttachment[];
  notes?: string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
};

/** What you may write when creating or updating a record in the "Warehouse Receipts" table. */
export type WarehouseReceiptsRecordInput = {
  receiptNumber: string | null;
  entity: string | string[] | null;
  program: string | string[] | null;
  loan: string | string[] | null;
  warehouseName: string | null;
  warehouseLocation: string | null;
  commodityType: string | null;
  grade: string | null;
  quantity: string | number | null;
  unitOfMeasure: string | null;
  unitPrice: string | number | null;
  totalValue: string | number | null;
  dateDeposited: string | Date | null;
  expiryDate: string | Date | null;
  status: "Active" | "Released" | "Expired" | "Pledged" | string | null;
  collateralManager: string | null;
  receiptDocument: ZiteAttachmentInput[] | ZiteAttachmentInput | null;
  notes: string | null;
};

/** A record in the "Reminder Templates" table, as it is read back. */
export type ReminderTemplatesRecordType = {
  id: string;
  /** Primary field. "Template Name" */
  templateName?: string;
  category?: "Overdue Payment" | "Document Request" | "Limit Expiry" | "Onboarding Follow-up" | "Offer Expiry" | "General" | string;
  subject?: string;
  body?: string;
  channel?: "In-App Notification" | "Email" | "SMS" | string;
  active?: boolean;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  /** Read-only. "Updated At". Auto-set when record was last modified (ISO 8601) */
  updatedAt?: string;
};

/** What you may write when creating or updating a record in the "Reminder Templates" table. */
export type ReminderTemplatesRecordInput = {
  templateName: string | null;
  category: "Overdue Payment" | "Document Request" | "Limit Expiry" | "Onboarding Follow-up" | "Offer Expiry" | "General" | string | null;
  subject: string | null;
  body: string | null;
  channel: "In-App Notification" | "Email" | "SMS" | string | null;
  active: string | boolean | null;
};

/** A record in the "API Partners" table, as it is read back. */
export type ApiPartnersRecordType = {
  id: string;
  /** Primary field. "Partner Name" */
  partnerName?: string;
  partnerType?: "FI" | "Master Anchor" | "Fintech" | string;
  status?: "Pending Approval" | "Active" | "Suspended" | "Revoked" | string;
  contactName?: string;
  contactEmail?: string;
  contactPhone?: string;
  companyRegistration?: string;
  country?: string;
  website?: string;
  enabledProducts?: ("Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string)[];
  sandboxEnabled?: boolean;
  productionEnabled?: boolean;
  approvedBy?: string;
  /** "Approved At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  approvedAt?: string;
  notes?: string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  /** Read-only. "Updated At". Auto-set when record was last modified (ISO 8601) */
  updatedAt?: string;
  /** Links to apiKeys ("API Keys"). "API Keys" */
  apiKeys?: string | string[];
  /** Links to apiActivityLog ("API Activity Log"). "API Activity Log" */
  apiActivityLog?: string | string[];
  /** Links to backofficeUsers ("Backoffice Users"). "Backoffice Users" */
  backofficeUsers?: string | string[];
  /** Links to entities ("Entities"). "Entities" */
  entities?: string | string[];
  /** Links to programs ("Programs"). "Programs" */
  programs?: string | string[];
};

/** What you may write when creating or updating a record in the "API Partners" table. */
export type ApiPartnersRecordInput = {
  partnerName: string | null;
  partnerType: "FI" | "Master Anchor" | "Fintech" | string | null;
  status: "Pending Approval" | "Active" | "Suspended" | "Revoked" | string | null;
  contactName: string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  companyRegistration: string | null;
  country: string | null;
  website: string | null;
  enabledProducts: "Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string | ("Invoice Finance" | "Reverse Factoring" | "Invoice Discounting" | "Blended Finance" | "Leasing" | "Warehouse Receipt" | string)[] | null;
  sandboxEnabled: string | boolean | null;
  productionEnabled: string | boolean | null;
  approvedBy: string | null;
  approvedAt: string | Date | null;
  notes: string | null;
  apiKeys: string | string[] | null;
  apiActivityLog: string | string[] | null;
  backofficeUsers: string | string[] | null;
  entities: string | string[] | null;
  programs: string | string[] | null;
};

/** A record in the "API Keys" table, as it is read back. */
export type ApiKeysRecordType = {
  id: string;
  /** Primary field. "Key Prefix" */
  keyPrefix?: string;
  /** Links to apiPartners ("API Partners"). "API Partner" */
  apiPartner?: string | string[];
  environment?: "Sandbox" | "Production" | string;
  keyHash?: string;
  keyHint?: string;
  label?: string;
  status?: "Active" | "Revoked" | "Expired" | string;
  /** "Last Used At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastUsedAt?: string;
  /** "Revoked At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  revokedAt?: string;
  revokedBy?: string;
  /** "Expires At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  expiresAt?: string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
  /** Links to apiActivityLog ("API Activity Log"). "API Activity Log" */
  apiActivityLog?: string | string[];
};

/** What you may write when creating or updating a record in the "API Keys" table. */
export type ApiKeysRecordInput = {
  keyPrefix: string | null;
  apiPartner: string | string[] | null;
  environment: "Sandbox" | "Production" | string | null;
  keyHash: string | null;
  keyHint: string | null;
  label: string | null;
  status: "Active" | "Revoked" | "Expired" | string | null;
  lastUsedAt: string | Date | null;
  revokedAt: string | Date | null;
  revokedBy: string | null;
  expiresAt: string | Date | null;
  apiActivityLog: string | string[] | null;
};

/** A record in the "API Activity Log" table, as it is read back. */
export type ApiActivityLogRecordType = {
  id: string;
  /** Primary field. Read-only. "Log ID" */
  logId?: number;
  /** Links to apiPartners ("API Partners"). "API Partner" */
  apiPartner?: string | string[];
  /** Links to apiKeys ("API Keys"). "API Key" */
  apiKey?: string | string[];
  environment?: "Sandbox" | "Production" | string;
  endpoint?: string;
  method?: "GET" | "POST" | "PUT" | "DELETE" | string;
  /** "Status Code". 0 decimal places, format: local (e.g. 1,000,000.50) */
  statusCode?: number;
  /** Links to entities ("Entities"). "Entity Created" */
  entityCreated?: string | string[];
  requestSummary?: string;
  errorMessage?: string;
  ipAddress?: string;
  /** Read-only. "Created At". Auto-set when record was created (ISO 8601) */
  createdAt?: string;
};

/** What you may write when creating or updating a record in the "API Activity Log" table. */
export type ApiActivityLogRecordInput = {
  apiPartner: string | string[] | null;
  apiKey: string | string[] | null;
  environment: "Sandbox" | "Production" | string | null;
  endpoint: string | null;
  method: "GET" | "POST" | "PUT" | "DELETE" | string | null;
  statusCode: string | number | null;
  entityCreated: string | string[] | null;
  requestSummary: string | null;
  errorMessage: string | null;
  ipAddress: string | null;
};

export interface NotificationLink {
  path?: string;
  params?: Record<string, string>;
}

export interface NotificationsCreateParams {
  recipients: string[];
  title: string;
  body?: string;
  link?: NotificationLink;
  path?: string;
  params?: Record<string, string>;
  payload?: Record<string, unknown>;
  idempotencyKey?: string;
}

export type NotificationsCreateResult =
  | { created: number }
  | { created: 0; preview: true; wouldCreate: number };

export interface ZiteAuthUser {
  id: string;
  name: string;
  email: string;
  firstName?: string;
  lastName?: string;
  image: string | null;
}

export const zite = {
  invitations: createTableClient<InvitationsRecordType, InvitationsRecordInput>('Invitations'), // "Invitations"
  notifications: createTableClient<NotificationsRecordType, NotificationsRecordInput>('Notifications'), // "Notifications"
  systemSettings: createTableClient<SystemSettingsRecordType, SystemSettingsRecordInput>('SystemSettings'), // "System Settings"
  backofficeUsers: createTableClient<BackofficeUsersRecordType, BackofficeUsersRecordInput>('BackofficeUsers'), // "Backoffice Users"
  entities: createTableClient<EntitiesRecordType, EntitiesRecordInput>('Entities'), // "Entities"
  programs: createTableClient<ProgramsRecordType, ProgramsRecordInput>('Programs'), // "Programs"
  loans: createTableClient<LoansRecordType, LoansRecordInput>('Loans'), // "Loans"
  transactions: createTableClient<TransactionsRecordType, TransactionsRecordInput>('Transactions'), // "Transactions"
  onboardings: createTableClient<OnboardingsRecordType, OnboardingsRecordInput>('Onboardings'), // "Onboardings"
  onboardingDocuments: createTableClient<OnboardingDocumentsRecordType, OnboardingDocumentsRecordInput>('OnboardingDocuments'), // "Onboarding Documents"
  entityOwners: createTableClient<EntityOwnersRecordType, EntityOwnersRecordInput>('EntityOwners'), // "Entity Owners"
  entityOperators: createTableClient<EntityOperatorsRecordType, EntityOperatorsRecordInput>('EntityOperators'), // "Entity Operators"
  limitProposals: createTableClient<LimitProposalsRecordType, LimitProposalsRecordInput>('LimitProposals'), // "Limit Proposals"
  invoices: createTableClient<InvoicesRecordType, InvoicesRecordInput>('Invoices'), // "Invoices"
  financingRequests: createTableClient<FinancingRequestsRecordType, FinancingRequestsRecordInput>('FinancingRequests'), // "Financing Requests"
  offerLetters: createTableClient<OfferLettersRecordType, OfferLettersRecordInput>('OfferLetters'), // "Offer Letters"
  financialInstitutions: createTableClient<FinancialInstitutionsRecordType, FinancialInstitutionsRecordInput>('FinancialInstitutions'), // "Financial Institutions"
  fiProgramPricing: createTableClient<FiProgramPricingRecordType, FiProgramPricingRecordInput>('FiProgramPricing'), // "FI Program Pricing"
  glAccounts: createTableClient<GlAccountsRecordType, GlAccountsRecordInput>('GlAccounts'), // "GL Accounts"
  journalEntries: createTableClient<JournalEntriesRecordType, JournalEntriesRecordInput>('JournalEntries'), // "Journal Entries"
  journalLines: createTableClient<JournalLinesRecordType, JournalLinesRecordInput>('JournalLines'), // "Journal Lines"
  creditScores: createTableClient<CreditScoresRecordType, CreditScoresRecordInput>('CreditScores'), // "Credit Scores"
  riskAlerts: createTableClient<RiskAlertsRecordType, RiskAlertsRecordInput>('RiskAlerts'), // "Risk Alerts"
  bankAccounts: createTableClient<BankAccountsRecordType, BankAccountsRecordInput>('BankAccounts'), // "Bank Accounts"
  assetSchedules: createTableClient<AssetSchedulesRecordType, AssetSchedulesRecordInput>('AssetSchedules'), // "Asset Schedules"
  warehouseReceipts: createTableClient<WarehouseReceiptsRecordType, WarehouseReceiptsRecordInput>('WarehouseReceipts'), // "Warehouse Receipts"
  reminderTemplates: createTableClient<ReminderTemplatesRecordType, ReminderTemplatesRecordInput>('ReminderTemplates'), // "Reminder Templates"
  apiPartners: createTableClient<ApiPartnersRecordType, ApiPartnersRecordInput>('ApiPartners'), // "API Partners"
  apiKeys: createTableClient<ApiKeysRecordType, ApiKeysRecordInput>('ApiKeys'), // "API Keys"
  apiActivityLog: createTableClient<ApiActivityLogRecordType, ApiActivityLogRecordInput>('ApiActivityLog'), // "API Activity Log"
  sql: createSqlClient(),
  auth: createAuthClient<ZiteAuthUser>(),
};
